*-------------------------------------------------------------------------*
*                                                                          
*                     SPSS SETUP FILE FOR ICPSR 36164
*         LAW ENFORCEMENT MANAGEMENT AND ADMINISTRATIVE STATISTICS
*                              (LEMAS), 2013
* 
*
*  SPSS setup sections are provided for the ASCII version of this data
*  collection.  These sections are listed below:
*
*  DATA LIST:  assigns the name, type, decimal specification (if any),
*  and specifies the beginning and ending column locations for each
*  variable in the data file. Users must replace the "data-filename"
*  in the DATA LIST statement with a filename specifying the directory
*  on the user's computer system in which the downloaded and unzipped
*  data file is physically located (e.g., "c:\temp\36164-0001-data.txt").
*
*  VARIABLE LABELS:  assigns descriptive labels to all variables.
*  Labels and variable names may be identical for some data files.
*
*  MISSING VALUES: declares user-defined missing values. Not all
*  variables in this data set necessarily have user-defined missing
*  values. These values can be treated specially in data transformations,
*  statistical calculations, and case selection.
*
*  VALUE LABELS: assigns descriptive labels to codes found in the data
*  file.  Not all codes necessarily have assigned value labels.
*
*  VARIABLE LEVEL: assigns measurement level to each variable (scale,
*  nominal, or ordinal).
*
*  NOTE:  Users should modify this setup file to suit their specific
*  needs. The MISSING VALUES section has been commented out (i.e., '*').
*  To include the MISSING VALUES section in the final SPSS setup, remove
*  the comment indicators from the desired section.
*
*  CREATING A PERMANENT SPSS DATA FILE: If users wish to create and save
*  an SPSS data file for further analysis using SPSS for Windows, the
*  necessary "SAVE OUTFILE" command is provided in the last line of
*  this file.  To activate the command, users must delete the leading
*  asterisk (*) and replace "spss-filename" with a filename specifying
*  the location on the user's computer system to which the new data file
*  will be saved (e.g., SAVE OUTFILE="c:\spsswin\data\da36164-0001.sav").
*
*-------------------------------------------------------------------------.

* SPSS FILE HANDLE AND DATA LIST COMMANDS.

FILE HANDLE DATA / NAME="data-filename" LRECL=5639.
DATA LIST FILE=DATA /
            ORI7 1-7 (A)           ORI9 8-16 (A)
      SHERIFF_FLAG 17-18             TYPE 19 (A)          TRIBALPD 20-21
          COUNTYPD 22-23      AGENCYID 24-35 (A) BJS_AGENCYNAME 36-135 (A)
        CITY 136-175 (A)   STATENAME 176-195 (A)   STATECODE 196-197 (A)
     ZIPCODE 198-202 (A)         POP2012 203-210 SAMPLETYPE_FINAL 211-230 (A)
       STRATCODE 231-233         FTSWORN 234-238           FTCIV 239-243
         PTSWORN 244-246           PTCIV 247-250   PERS_PDSW_MFT 251-255
   PERS_PDSW_MPT 256-258   PERS_PDSW_FFT 259-262   PERS_PDSW_FPT 263-265
    PERS_FTS_WHT 266-270    PERS_FTS_BLK 271-274    PERS_FTS_HSP 275-278
    PERS_FTS_IND 279-280    PERS_FTS_ASN 281-284    PERS_FTS_HAW 285-287
    PERS_FTS_TWO 288-291    PERS_FTS_UNK 292-294 PERS_FTS_RACETOT 295-302 (2)
 PERS_RESP_PATRL 303-306 PERS_RESP_INVST 307-310  PERS_RESP_JAIL 311-314
   PERS_RESP_CRT 315-318  PERS_RESP_OTHR 319-322  PERS_SUP_CHF_M 323-324
  PERS_SUP_CHF_F 325-326 PERS_SUP_INTM_M 327-330 PERS_SUP_INTM_F 331-333
  PERS_SUP_SGT_M 334-337  PERS_SUP_SGT_F 338-340     PERS_SSW_FT 341-343
     PERS_SSW_PT 344-346       PERS_UPSW 347-350   PERS_DUT_NONE 351-352
   PERS_DUT_ADMN 353-354    PERS_DUT_CLN 355-356    PERS_DUT_LGL 357-358
   PERS_DUT_ACCT 359-360   PERS_DUT_FSCI 361-362  PERS_DUT_RSRCH 363-364
     PERS_DUT_HR 365-366     PERS_DUT_IT 367-368     PERS_DUT_VM 369-370
     PERS_DUT_CD 371-372    PERS_DUT_CRT 373-374   PERS_DUT_JAIL 375-376
   PERS_DUT_OTHR 377-378 PERS_DUT_SPEC 379-578 (A) PAY_SAL_EXC_MIN 579-584
 PAY_SAL_EXC_MAX 585-590 PAY_SAL_SGT_MIN 591-596 PAY_SAL_SGT_MAX 597-602
 PAY_SAL_OFCR_MIN 603-608 PAY_SAL_OFCR_MAX 609-614    PAY_INCT_EDU 615-616
    PAY_INCT_VOC 617-618   PAY_INCT_LANG 619-620   PAY_INCT_SPCL 621-622
   PAY_INCT_HZRD 623-624     PAY_INCT_SD 625-626   PAY_INCT_RINC 627-628
    PAY_INCT_MRT 629-630   PAY_INCT_OTHR 631-632 PAY_INCT_SPEC 633-832 (A)
         PAY_OUT 833-834      PAY_RST_NO 835-836     PAY_RST_HRS 837-838
    PAY_RST_TYPE 839-840    PAY_RST_OTHR 841-842 PAY_RST_SPEC 843-1042 (A)
      PAY_BARG 1043-1044     PAY_SBARG 1045-1046  PAY_RMB_TUIT 1047-1048
   PAY_RMB_UNF 1049-1050  PAY_RMB_ARMR 1051-1052  PAY_RMB_SFTY 1053-1054
  PAY_RMB_FIRE 1055-1056   PAY_OVER_SW 1057-1058  PAY_OVER_NSW 1059-1060
  PAY_FUNC_CRT 1061-1062 PAY_FUNC_SHFT 1063-1064 PAY_FUNC_PTRL 1065-1066
 PAY_FUNC_INVS 1067-1068 PAY_FUNC_ADMN 1069-1070 PAY_FUNC_EMRG 1071-1072
 PAY_FUNC_EVNT 1073-1074 PAY_FUNC_OTHR 1075-1076 PAY_FUNC_SPEC 1077-1276 (A)
       PAY_LMT 1277-1278   PAY_VEH_MRK 1279-1280  PAY_VEH_UMRK 1281-1282
       HIR_FRZ 1283-1284  HIR_MTH_SW10 1285-1286  HIR_MTH_SW11 1287-1288
  HIR_MTH_SW12 1289-1290 HIR_MTH_NSW10 1291-1295 (2) HIR_MTH_NSW11 1296-1299 (1)
 HIR_MTH_NSW12 1300-1303 (1)       HIR_NBR 1304-1305 HIR_NBR_DRCT_FT 1306-1309
 HIR_NBR_DRCT_PT 1310-1311 HIR_NBR_PRE_FT 1312-1313 HIR_NBR_PRE_PT 1314-1315
 HIR_NBR_LAT_FT 1316-1317 HIR_NBR_LAT_PT 1318-1319   HIR_NBR_TFT 1320-1323
   HIR_NBR_TPT 1324-1325  HIR_TRN_NO_L 1326-1327  HIR_TRN_NO_P 1328-1329
 HIR_TRN_CRS_L 1330-1331 HIR_TRN_CRS_P 1332-1333 HIR_TRN_FLD_L 1334-1335
 HIR_TRN_FLD_P 1336-1337 HIR_TRN_DIR_L 1338-1339 HIR_TRN_DIR_P 1340-1341
 HIR_TRN_OLATS 1342-1541 (A) HIR_TRN_OPRES 1542-1741 (A)   HIR_NSWT_NO 1742-1743
 HIR_NSWT_VAR_FT 1744-1746 HIR_NSWT_VAR_PT 1747-1751 (1)    HIR_EDU_NO 1752-1753
    HIR_EDU_HS 1754-1755  HIR_EDU_SCOL 1756-1757    HIR_EDU_AD 1758-1759
    HIR_EDU_BD 1760-1761  HIR_EDU_OTHR 1762-1763 HIR_EDU_SPEC 1764-1963 (A)
       HIR_MIL 1964-1965    HIR_BD_VAR 1966-1968    HIR_RTR_DB 1969-1970
    HIR_RTR_DC 1971-1972    HIR_RTR_SS 1973-1974  HIR_RTR_OTHR 1975-1976
 HIR_RTR_SPEC 1977-2176 (A)  HIR_SEP_NMED 2177-2180   HIR_SEP_MED 2181-2182
   HIR_SEP_VOL 2183-2185 HIR_SEP_LAYOFF 2186-2187   HIR_SEP_DIS 2188-2189
  HIR_SEP_OTHR 2190-2192   HIR_SEP_TTL 2193-2196 HIR_SEPNS_LAYOFF 2197-2198
 HIR_SEPNS_OTHR 2199-2202 HIR_SEPNS_TTL 2203-2206     BDGT_MNTH 2207-2208
      BDGT_TTL 2209-2218  BDGT_TTL_EST 2219-2220  BDGT_SRC_MNC 2221-2222
 BDGT_SRC_CNTY 2223-2224 BDGT_SRC_STATE 2225-2226  BDGT_SRC_FED 2227-2228
 BDGT_SRC_CONT 2229-2230 BDGT_SRC_ASST 2231-2232  BDGT_SRC_FEE 2233-2234
 BDGT_SRC_OTHR 2235-2236 BDGT_SRC_SPEC 2237-2436 (A)      BDGT_RED 2437-2438
 BDGT_PCT_SW 2439-2443 (2) BDGT_PCT_NSW 2444-2448 (2)      BDGT_FUR 2449-2450
 BDGT_FUR2_SW10 2451-2454 BDGT_FUR2_SW11 2455-2458 BDGT_FUR2_SW12 2459-2462
 BDGT_FUR2_NSW10 2463-2466 BDGT_FUR2_NSW11 2467-2470 BDGT_FUR2_NSW12 2471-2474
       COM_MIS 2475-2476   COM_TRN_REC 2477-2478 COM_TRN_INSRV 2479-2480
      COM_SARA 2481-2482     COM_NSARA 2483-2486       COM_COL 2487-2488
      COM_PTNR 2489-2490        COM_BT 2491-2492       COM_NBT 2493-2496
      COM_SURV 2497-2498  TECH_TYP_GUN 2499-2500  TECH_TYP_LIC 2501-2502
 TECH_TYP_SMRT 2503-2504 TECH_TYP_VPUB 2505-2506 TECH_TYP_VVEH 2507-2508
 TECH_TYP_VPAT 2509-2510 TECH_TYP_VWPN 2511-2512 TECH_TYP_VOTHR 2513-2514
 TECH_EAC_MREC 2515-2516 TECH_EAC_DREC 2517-2518 TECH_EAC_CRIM 2519-2520
 TECH_EAC_WARR 2521-2522 TECH_EAC_PROT 2523-2524 TECH_EAC_ADRS 2525-2526
      TECH_CIR 2527-2528 TECH_CIR_SPEC 2529-2728 (A)      TECH_CRS 2729-2730
 TECH_CREC_INC 2731-2732 TECH_CREC_SUM 2733-2734 TECH_CREC_NAR 2735-2736
 TECH_CREC_OTHR 2737-2738 TECH_CREC_SPEC 2739-2938 (A)  TECH_REC_NAR 2939-2940
 TECH_REC_CODE 2941-2942 TECH_REC_STAT 2943-2944  TECH_REC_VIC 2945-2946
  TECH_REC_SUS 2947-2948  TECH_REC_LOC 2949-2950  TECH_REC_GEO 2951-2952
 TECH_REC_DATE 2953-2954   TECH_WHO_NO 2955-2956 TECH_WHO_STAFF 2957-2958
 TECH_WHO_EXTR 2959-2960 TECH_MANY_FTS 2961-2963 TECH_MANY_PTS 2964-2966
 TECH_MANY_FTNS 2967-2969 TECH_MANY_PTNS 2970-2971  TECH_OUT_LAW 2972-2973
  TECH_OUT_GOV 2974-2975 TECH_OUT_UNIV 2976-2977 TECH_OUT_VEND 2978-2979
 TECH_OUT_OTHR 2980-2981 TECH_OUT_OTHR_SPEC 2982-3181 (A) TECH_WEB_NONE 3182-3183
  TECH_WEB_JUR 3184-3185 TECH_WEB_BEAT 3186-3187  TECH_WEB_MAP 3188-3189
 TECH_WEB_OFFND 3190-3191 TECH_WEB_OTHR 3192-3193 TECH_WEB_SPEC 3194-3393 (A)
 TECH_PUBL_REP 3394-3395 TECH_PUBL_ASK 3396-3397 TECH_PUBL_FILE 3398-3399
 TECH_PUBL_OTHR 3400-3401 TECH_PUBL_SPEC 3402-3601 (A)     TECH_REPT 3602-3603
     TECH_RECV 3604-3605 TECH_MEDIA_TW 3606-3607 TECH_MEDIA_FB 3608-3609
 TECH_MEDIA_BLOG 3610-3611 TECH_MEDIA_YTBE 3612-3613 TECH_MEDIA_MASS 3614-3615
 TECH_MEDIA_OTHR 3616-3617 TECH_MEDIA_SPEC 3618-3817 (A)   VEH_OPRT_MK 3818-3821
 VEH_OPRT_UNMK 3822-3825   VEH_TYP_MTR 3826-3827   VEH_TYP_ATV 3828-3829
   VEH_TYP_AIR 3830-3831  VEH_TYP_HCOP 3832-3833  VEH_TYP_BOAT 3834-3835
 VEH_TYP_DRONE 3836-3837  VEH_TYP_OTHR 3838-3839 VEH_TYP_SPEC 3840-4039 (A)
      VEH_WPUR 4040-4041 VEH_WPUR_SPEC 4042-4241 (A)       VEH_DOC 4242-4243
 VEH_DOC_SPEC 4244-4443 (A)      VEH_NPUR 4444-4447  VEH_NPUR_EST 4448-4449
  VEH_NPUR_UNK 4450-4451   VEH_REST_NO 4452-4453  VEH_REST_ALN 4454-4455
 VEH_REST_VISL 4456-4457 VEH_REST_SEPR 4458-4459 VEH_REST_RADIO 4460-4461
  VEH_REST_ARM 4462-4463 VEH_REST_OTHR 4464-4465 VEH_REST_SPEC 4466-4665 (A)
      VEH_CNTN 4666-4667 SAFE_AUTH_HGN 4668-4669 SAFE_AUTH_RFL 4670-4671
 SAFE_AUTH_SGN 4672-4673 SAFE_AUTH_BTN 4674-4675 SAFE_AUTH_IMP 4676-4677
 SAFE_AUTH_SOFT 4678-4679 SAFE_AUTH_SPRAY 4680-4681 SAFE_AUTH_CHEM 4682-4683
 SAFE_AUTH_TASR 4684-4685 SAFE_AUTH_NECK 4686-4687 SAFE_AUTH_TKDWN 4688-4689
 SAFE_AUTH_OHAND 4690-4691 SAFE_AUTH_CHAND 4692-4693 SAFE_AUTH_LEG 4694-4695
 SAFE_DOC_DISF 4696-4697 SAFE_DOC_DCHF 4698-4699  SAFE_DOC_BAT 4700-4701
  SAFE_DOC_IMP 4702-4703 SAFE_DOC_SOFT 4704-4705 SAFE_DOC_SPRAY 4706-4707
 SAFE_DOC_CHEM 4708-4709 SAFE_DOC_DIST 4710-4711 SAFE_DOC_DCHT 4712-4713
 SAFE_DOC_NECK 4714-4715 SAFE_DOC_TKDWN 4716-4717 SAFE_DOC_OHAND 4718-4719
 SAFE_DOC_CHAND 4720-4721  SAFE_DOC_LEG 4722-4723     SAFE_FINC 4724-4725
 SAFE_FINC_SPEC 4726-4925 (A) NO_RECORD_FORCE 4926-4927  SAFE_FRC_INC 4928-4929
 SAFE_FRC_OFFC 4930-4931 SAFE_FRC_OTHR 4932-4933 SAFE_FRC_SPEC 4934-5133 (A)
     SAFE_FTTL 5134-5137 SAFE_FTTL_EST 5138-5139 SAFE_FTTL_UNK 5140-5141
     SAFE_SEPR 5142-5147 SAFE_SEPR_EST 5148-5149 SAFE_SEPR_UNK 5150-5151
     SAFE_ARMR 5152-5153 SAFE_ARMR_OTHRS 5154-5155 SAFE_RQUR_ACC 5156-5157
 SAFE_RQUR_RSK 5158-5159 SAFE_RQUR_ALL 5160-5161 SAFE_RQUR_CSTM 5162-5163
 SAFE_RQUR_TRN 5164-5165 SAFE_RQUR_COMP 5166-5167 SAFE_RQUR_BLST 5168-5169
 NO_BODY_ARMOR 5170-5171  SAFE_PAY_DPT 5172-5173  SAFE_PAY_IND 5174-5175
 SAFE_PAY_GRNT 5176-5177 SAFE_PAY_OTHR 5178-5179 SAFE_PAY_SPEC 5180-5379 (A)
 ISSU_ADDR_BIAS 5380-5381 ISSU_ADDR_BOMB 5382-5383 ISSU_ADDR_ABSE 5384-5385
 ISSU_ADDR_CYBR 5386-5387 ISSU_ADDR_DPV 5388-5389 ISSU_ADDR_TERR 5390-5391
 ISSU_ADDR_TRAF 5392-5393 ISSU_ADDR_DUI 5394-5395 ISSU_ADDR_JUV 5396-5397
 ISSU_ADDR_GANG 5398-5399 ISSU_ADDR_REEN 5400-5401 ISSU_ADDR_FUG 5402-5403
 ISSU_ADDR_VIC 5404-5405 ISSU_ADDR_SWAT 5406-5407     ISSU_SPEC 5408-5410
    ISSU_MULTI 5411-5412 ISSU_TASK_SWAT 5413-5414 ISSU_TASK_DRUG 5415-5416
 ISSU_TASK_GANG 5417-5418 ISSU_TASK_TRAF 5419-5420 ISSU_TASK_OTHR 5421-5422
 ISSU_TASK_SPEC 5423-5622 (A)    BASEWT 5623-5628 (3)  NRADJUST 5629-5633 (3)
   FINALWT 5634-5639 (3)
   .

* SPSS VARIABLE LABELS COMMAND

VARIABLE LABELS
   ORI7      'AGENCY ORIGINATING RECORD IDENTIFIER ASSIGNED BY FBI (7 CHARACTER)' /
   ORI9      'AGENCY ORIGINATING RECORD IDENTIFIER ASSIGNED BY FBI (9 CHARACTER)' /
   SHERIFF_FLAG 'SOURCE OF SWORN AND CIVILIAN PERSONNEL TOTALS FOR SHERIFFS'' OFFICES' /
   TYPE      'TYPE OF AGENCY' /
   TRIBALPD  'TRIBAL POLICE INDICATOR' /
   COUNTYPD  'COUNTY POLICE INDICATOR' /
   AGENCYID  'AGENCY ID' /
   BJS_AGENCYNAME 'AGENCY NAME IN BJS UNIVERSE FILE' /
   CITY      'CITY' /
   STATENAME 'STATE' /
   STATECODE 'STATE ABBREVIATION' /
   ZIPCODE   'ZIP CODE' /
   POP2012   'CENSUS BUREAU POPULATION ESTIMATE FOR 2012' /
   SAMPLETYPE_FINAL 'SAMPLING STRATUM DESCRIPTION' /
   STRATCODE 'STRATUM NUMERIC CODE' /
   FTSWORN   'A1C.TOTAL NUMBER OF SWORN PERSONNEL ? FULL-TIME' /
   FTCIV     'A7FT.NUMBER OF PAID NONSWORN FULL-TIME PERSONNEL' /
   PTSWORN   'A1C.TOTAL NUMBER OF SWORN PERSONNEL ? PART TIME' /
   PTCIV     'A7PT.NUMBER OF PAID NONSWORN PART TIME PERSONNEL' /
   PERS_PDSW_MFT 'A1A.NUMBER OF MALE SWORN PERSONNEL ? FULL-TIME' /
   PERS_PDSW_MPT 'A1A.NUMBER OF MALE SWORN PERSONNEL ? PART TIME' /
   PERS_PDSW_FFT 'A1B.NUMBER OF FEMALE SWORN PERSONNEL ? FULL-TIME' /
   PERS_PDSW_FPT 'A1B.NUMBER OF FEMALE SWORN PERSONNEL ? PART TIME' /
   PERS_FTS_WHT 'A2A.NUMBER OF FULL-TIME SWORN PERSONNEL ? WHITE' /
   PERS_FTS_BLK 'A2B.NUMBER OF FULL-TIME SWORN PERSONNEL ? BLACK' /
   PERS_FTS_HSP 'A2C.NUMBER OF FULL-TIME SWORN PERSONNEL ? HISPANIC OR LATINO' /
   PERS_FTS_IND 'A2D.NUMBER OF FULL-TIME SWORN PERSONNEL ? AMERICAN INDIAN OR ALASKAN NATIVE' /
   PERS_FTS_ASN 'A2E.NUMBER OF FULL-TIME SWORN PERSONNEL ? ASIAN' /
   PERS_FTS_HAW 'A2F.NUMBER OF FULL-TIME SWORN PERSONNEL ? HAWAIIAN' /
   PERS_FTS_TWO 'A2G.NUMBER OF FULL-TIME SWORN PERSONNEL ? TWO OR MORE RACES' /
   PERS_FTS_UNK 'A2H.NUMBER OF FULL-TIME SWORN PERSONNEL ? RACE UNKNOWN' /
   PERS_FTS_RACETOT 'A2I.TOTAL NUMBER OF FULL-TIME SWORN PERSONNEL BY RACE' /
   PERS_RESP_PATRL 'A3A.PRIMARY DUTY ? PATROL' /
   PERS_RESP_INVST 'A3B.PRIMARY DUTY ? INVESTIGATIVE' /
   PERS_RESP_JAIL 'A3C.PRIMARY DUTY ? JAIL-RELATED' /
   PERS_RESP_CRT 'A3D.PRIMARY DUTY ? COURT-RELATED' /
   PERS_RESP_OTHR 'A3E.PRIMARY DUTY ? OTHER' /
   PERS_SUP_CHF_M 'A4A.NUMBER OF SUPERVISORY FULL-TIME SWORN PERSONNEL ? MALE CHIEF EXECUTIVE' /
   PERS_SUP_CHF_F 'A4A.NUMBER OF SUPERVISORY FULL-TIME SWORN PERSONNEL ? FEMALE CHIEF EXECUTIVE' /
   PERS_SUP_INTM_M 'A4B.NUMBER OF SUPERVISORY FULL-TIME SWORN PERSONNEL ? MALE INTERMEDIATE SUPERVISOR' /
   PERS_SUP_INTM_F 'A4B.NUMBER OF SUPERVISORY FULL-TIME SWORN PERSONNEL ? FEMALE INTERMEDIATE SUPERVISOR' /
   PERS_SUP_SGT_M 'A4C.NUMBER OF SUPERVISORY FULL-TIME SWORN PERSONNEL ? MALE SERGEANT OR EQUIVALENT FIRST-LINE SUPERVISOR' /
   PERS_SUP_SGT_F 'A4C.NUMBER OF SUPERVISORY FULL-TIME SWORN PERSONNEL ? FEMALE SERGEANT OR EQUIVALENT FIRST-LINE SUPERVISOR' /
   PERS_SSW_FT 'A5.NUMBER OF SEASONAL SWORN FULL-TIME PERSONNEL' /
   PERS_SSW_PT 'A5.NUMBER OF SEASONAL SWORN PART TIME PERSONNEL' /
   PERS_UPSW 'A6.NUMBER OF UNPAID SWORN RESERVE/AUXILIARY OFFICERS' /
   PERS_DUT_NONE 'A8NA.AGENCY DOES NOT EMPLOY NONSWORN PERSONNEL' /
   PERS_DUT_ADMN 'A8A.NONSWORN PERSONNEL PERFORMED ADMINISTRATIVE DUTIES' /
   PERS_DUT_CLN 'A8B.NONSWORN PERSONNEL PERFORMED CLEANING DUTIES' /
   PERS_DUT_LGL 'A8C.NONSWORN PERSONNEL PERFORMED LEGAL DUTIES' /
   PERS_DUT_ACCT 'A8D.NONSWORN PERSONNEL PERFORMED ACCOUNTING DUTIES' /
   PERS_DUT_FSCI 'A8E.NONSWORN PERSONNEL PERFORMED FORENSIC SCIENCE DUTIES' /
   PERS_DUT_RSRCH 'A8F.NONSWORN PERSONNEL PERFORMED RESEARCH, STATISTICS, OR CRIME ANALYSIS DUTIES' /
   PERS_DUT_HR 'A8G.NONSWORN PERSONNEL PERFORMED PERSONNEL/HUMAN RESOURCES DUTIES' /
   PERS_DUT_IT 'A8H.NONSWORN PERSONNEL PERFORMED INFORMATION TECHOLOGY SPECIALIST DUTIES' /
   PERS_DUT_VM 'A8H.NONSWORN PERSONNEL PERFORMED VEHICLE MAINTENANCE DUTIES' /
   PERS_DUT_CD 'A8I.NONSWORN PERSONNEL PERFORMED CALL DISPATCHER DUTIES' /
   PERS_DUT_CRT 'A8K.NONSWORN PERSONNEL PERFORMED COURT-RELATED DUTIES' /
   PERS_DUT_JAIL 'A8L.NONSWORN PERSONNEL PERFORMED JAIL-RELATED DUTIES' /
   PERS_DUT_OTHR 'A8M.NONSWORN PERSONNEL PERFORMED OTHER DUTIES' /
   PERS_DUT_SPEC 'A8TEXT.OTHER DUTIES PERFORMED BY NONSWORN PERSONNEL' /
   PAY_SAL_EXC_MIN 'B1A.MINIMUM SALARY OF CHIEF EXECUTIVE' /
   PAY_SAL_EXC_MAX 'B1A.MAXIMUM SALARY OF CHIEF EXECUTIVE' /
   PAY_SAL_SGT_MIN 'B1B.MINIMUM SALARY OF SERGEANT OR EQUIVALENT FIRST-LINE SUPERVISOR' /
   PAY_SAL_SGT_MAX 'B1B.MAXIMUM SALARY OF SERGEANT OR EQUIVALENT FIRST-LINE SUPERVISOR' /
   PAY_SAL_OFCR_MIN 'B1C.MINIMUM SALARY OF ENTRY-LEVEL OFFICER OR DEPUTY' /
   PAY_SAL_OFCR_MAX 'B1C.MAXIMUM SALARY OF ENTRY-LEVEL OFFICER OR DEPUTY' /
   PAY_INCT_EDU 'B2A.INCENTIVES FOR FULL-TIME SWORN PERSONNEL BASED ON EDUCATIONAL ACHIEVEMENT' /
   PAY_INCT_VOC 'B2B.INCENTIVES FOR FULL-TIME SWORN PERSONNEL BASED ON SPECIAL SKILLS OR VOCATIONAL TRAINING' /
   PAY_INCT_LANG 'B2C.INCENTIVES FOR FULL-TIME SWORN PERSONNEL BASED ON BI-LINGUAL OR MULTI-LINGUAL ABILITY' /
   PAY_INCT_SPCL 'B2D.INCENTIVES FOR FULL-TIME SWORN PERSONNEL BASED ON SPECIAL DUTY ASSIGNMENTS' /
   PAY_INCT_HZRD 'B2E.INCENTIVES FOR FULL-TIME SWORN PERSONNEL BASED ON HAZARDOUS DUTY ASSIGNMENTS' /
   PAY_INCT_SD 'B2F.INCENTIVES FOR FULL-TIME SWORN PERSONNEL BASED ON SHIFT DIFFERENTIAL' /
   PAY_INCT_RINC 'B2G.INCENTIVES FOR FULL-TIME SWORN PERSONNEL BASED ON RESIDENTIAL LOCATION' /
   PAY_INCT_MRT 'B2H.INCENTIVES FOR FULL-TIME SWORN PERSONNEL BASED ON MERIT/PERFORMANCE' /
   PAY_INCT_OTHR 'B2I.INCENTIVES FOR FULL-TIME SWORN PERSONNEL BASED ON OTHER CONSIDERATIONS' /
   PAY_INCT_SPEC 'B2TEXT.OTHER CONSIDERATIONS FOR FULL-TIME SWORN PERSONNEL INCENTIVES SPECIFIED' /
   PAY_OUT   'B3.PERSONNEL ALLOWED TO WORK OUTSIDE AGENCY IN A LAW ENFORCEMENT CAPACITY' /
   PAY_RST_NO 'B4.NO RESTRICTIONS PLACED ON FULL-TIME SWORN PERSONNEL WORKING OUTSIDE AGENCY IN A LAW ENFORCEMENT CAPACITY' /
   PAY_RST_HRS 'B4.NUMBER OF HOURS RESTRICTED FOR FULL-TIME SWORN PERSONNEL WORKING OUTSIDE AGENCY IN A LAW ENFORCEMENT CAPACITY' /
   PAY_RST_TYPE 'B4.TYPE OF ESTABLISHMENTS RESTRICTED FOR FULL-TIME SWORN PERSONNEL WORKING OUTSIDE AGENCY IN A LAW ENFORCEMENT CAPACITY' /
   PAY_RST_OTHR 'B4TEXT.OTHER RESTRICTIONS FOR FULL-TIME SWORN PERSONNEL WORKING OUTSIDE AGENCY IN A LAW ENFORCEMENT CAPACITY' /
   PAY_RST_SPEC 'SPECIFIC RESTRICTIONS FOR FULL-TIME SWORN PERSONNEL WORKING OUTSIDE AGENCY IN A LAW ENFORCEMENT CAPACITY' /
   PAY_BARG  'B5.SWORN PERSONNEL REPRESENTED BY COLLECTIVE BARGAINING ORGANIZATION' /
   PAY_SBARG 'B6.STATUS OF COLLECTIVE BARGAINING AGREEMENT' /
   PAY_RMB_TUIT 'B7A.TUITION COSTS REIMBURSED FOR FULL-TIME SWORN PERSONNEL' /
   PAY_RMB_UNF 'B7B.UNIFORM COSTS REIMBURSED FOR FULL-TIME SWORN PERSONNEL' /
   PAY_RMB_ARMR 'B7C.BODY ARMOR COSTS REIMBURSED FOR FULL-TIME SWORN PERSONNEL' /
   PAY_RMB_SFTY 'B7D.OTHER SAFETY EQUIPMENT COSTS REIMBURSED FOR FULL-TIME SWORN PERSONNEL' /
   PAY_RMB_FIRE 'B7E.PRIMARY FIREARM/SIDEARM COSTS REIMBURSED FOR FULL-TIME SWORN PERSONNEL' /
   PAY_OVER_SW 'B8A.SWORN PERSONNEL COMPENSATED FOR OVERTIME' /
   PAY_OVER_NSW 'B8B.NONSWORN PERSONNEL COMPENSATED FOR OVERTIME' /
   PAY_FUNC_CRT 'B9A.SWORN PERSONNEL AUTHORIZED TO WORK OVERTIME FOR COURT TESTIMONY' /
   PAY_FUNC_SHFT 'B9B.SWORN PERSONNEL AUTHORIZED TO WORK OVERTIME FOR EXTENDED SHIFTS' /
   PAY_FUNC_PTRL 'B9C.SWORN PERSONNEL AUTHORIZED TO WORK OVERTIME FOR INCREASED PATROL' /
   PAY_FUNC_INVS 'B9D.SWORN PERSONNEL AUTHORIZED TO WORK OVERTIME FOR INVESTIGATIONS' /
   PAY_FUNC_ADMN 'B9E.SWORN PERSONNEL AUTHORIZED TO WORK OVERTIME FOR ADMINISTRATIVE DUTIES' /
   PAY_FUNC_EMRG 'B9F.SWORN PERSONNEL AUTHORIZED TO WORK OVERTIME FOR EMERGENCY RESPONSE' /
   PAY_FUNC_EVNT 'B9G.SWORN PERSONNEL AUTHORIZED TO WORK OVERTIME FOR SPECIAL EVENTS' /
   PAY_FUNC_OTHR 'B9H.SWORN PERSONNEL AUTHORIZED TO WORK OVERTIME FOR OTHER FUNCTIONS' /
   PAY_FUNC_SPEC 'B9TEXT.OTHER FUNCTIONS AUTHORIZED FOR OVERTIME SPECIFIED' /
   PAY_LMT   'B10.LIMIT ON NUMBER OF OVERTIME HOURS WORKED BY SWORN PERSONNEL' /
   PAY_VEH_MRK 'B11A.SWORN PERSONNEL ALLOWED TO TAKE HOME AGENCY-OWNED MARKED VEHICLES' /
   PAY_VEH_UMRK 'B11B.SWORN PERSONNEL ALLOWED TO TAKE HOME AGENCY-OWNED UNMARKED VEHICLES' /
   HIR_FRZ   'C1.AGENCY IMPLEMENTED A HIRING FREEZE' /
   HIR_MTH_SW10 'C2A1.NUMBER OF MONTHS HIRING FREEZE IN EFFECT FOR SWORN PERSONNEL - 2010' /
   HIR_MTH_SW11 'C2A2.NUMBER OF MONTHS HIRING FREEZE IN EFFECT FOR SWORN PERSONNEL - 2011' /
   HIR_MTH_SW12 'C2A3.NUMBER OF MONTHS HIRING FREEZE IN EFFECT FOR SWORN PERSONNEL - 2012' /
   HIR_MTH_NSW10 'C2B1.NUMBER OF MONTHS HIRING FREEZE IN EFFECT FOR NONSWORN PERSONNEL - 2010' /
   HIR_MTH_NSW11 'C2B2.NUMBER OF MONTHS HIRING FREEZE IN EFFECT FOR NONSWORN PERSONNEL - 2011' /
   HIR_MTH_NSW12 'C2B3.NUMBER OF MONTHS HIRING FREEZE IN EFFECT FOR NONSWORN PERSONNEL - 2012' /
   HIR_NBR   'C3.NO NEW SWORN PERSONNEL HIRED' /
   HIR_NBR_DRCT_FT 'C3A1.NUMBER OF FULL-TIME DIRECT HIRES' /
   HIR_NBR_DRCT_PT 'C3A2.NUMBER OF PART TIME DIRECT HIRES' /
   HIR_NBR_PRE_FT 'C3B1.NUMBER OF FULL-TIME PRE-SERVICE HIRES' /
   HIR_NBR_PRE_PT 'C3B2.NUMBER OF PART TIME PRE-SERVICE HIRES' /
   HIR_NBR_LAT_FT 'C3C1.NUMBER OF FULL-TIME LATERAL HIRES' /
   HIR_NBR_LAT_PT 'C3C2.NUMBER OF PART TIME LATERAL HIRES' /
   HIR_NBR_TFT 'C3D1.TOTAL NEW FULL-TIME HIRES' /
   HIR_NBR_TPT 'C3D2.TOTAL NEW PART TIME HIRES' /
   HIR_TRN_NO_L 'C4A1.NO ADDITIONAL LAW ENFORCEMENT TRAINING FOR LATERAL HIRES' /
   HIR_TRN_NO_P 'C4A2.NO ADDITIONAL LAW ENFORCEMENT TRAINING FOR PRE-SERVICE HIRES' /
   HIR_TRN_CRS_L 'C4B1.ABBREVIATED TRAINING ON DEPARTMENTAL POLICIES FOR LATERAL HIRES' /
   HIR_TRN_CRS_P 'C4B2.ABBREVIATED TRAINING ON DEPARTMENTAL POLICIES FOR PRE-SERVICE HIRES' /
   HIR_TRN_FLD_L 'C4C1.ABBREVIATED FIELD SUPERVISION FOR LATERAL HIRES' /
   HIR_TRN_FLD_P 'C4C2.ABBREVIATED FIELD SUPERVISION FOR PRE-SERVICE HIRES' /
   HIR_TRN_DIR_L 'C4D1.SAME TRAINING AS DIRECT HIRES FOR LATERAL HIRES' /
   HIR_TRN_DIR_P 'CD42.SAME TRAINING AS DIRECT HIRES FOR PRE-SERVICE HIRES' /
   HIR_TRN_OLATS 'C4ETEXT.OTHER TRAINING FOR LATERAL HIRES - SPECIFIED' /
   HIR_TRN_OPRES 'C4FTEXT.OTHER TRAINING FOR PRE-SERVICE HIRES - SPECIFIED' /
   HIR_NSWT_NO 'C5.NO NONSWORN PERSONNEL HIRED' /
   HIR_NSWT_VAR_FT 'C5.NUMBER OF FULL-TIME NONSWORN PERSONNEL HIRED' /
   HIR_NSWT_VAR_PT 'C5.NUMBER OF PART TIME NONSWORN PERSONNEL HIRED' /
   HIR_EDU_NO 'C6-1.NO MINIMUM EDUCATION REQUIREMENT FOR NEW SWORN HIRES' /
   HIR_EDU_HS 'C6-2.HIGH SCHOOL DIPLOMA OR EQUIVALENT REQUIRED FOR NEW SWORN HIRES' /
   HIR_EDU_SCOL 'C6-3.SOME COLLEGE REQUIRED FOR NEW SWORN HIRES' /
   HIR_EDU_AD 'C6-4.ASSOCIATE''S DEGREE OR EQUIVALENT REQUIRED FOR NEW SWORN HIRES' /
   HIR_EDU_BD 'C6-5.BACHELOR''S DEGREE OR EQUIVALENT REQUIRED FOR NEW SWORN HIRES' /
   HIR_EDU_OTHR 'C6-6.OTHER EDUCATION REQUIREMENT FOR NEW SWORN HIRES' /
   HIR_EDU_SPEC 'C6TEXT.OTHER EDUCATION REQUIREMENT FOR NEW SWORN HIRES ? SPECIFIED' /
   HIR_MIL   'C7.MILITARY SERVICE ALTERNATIVE TO EDUCATION REQUIREMENTS FOR SWORN PERSONNEL' /
   HIR_BD_VAR 'C8.NUMBER OF FULL-TIME SWORN HIRES WITH A BACHELOR''S DEGREE OR HIGHER' /
   HIR_RTR_DB 'C9A.DEFINED BENEFITS RETIREMENT PLAN AVAILABLE TO FULL-TIME SWORN PERSONNEL' /
   HIR_RTR_DC 'C9B.DEFINED CONTRIBUTION PLAN AVAILABLE TO FULL-TIME SWORN PERSONNEL' /
   HIR_RTR_SS 'C9C.U.S. SOCIAL SECURITY PROGRAM AVAILABLE TO FULL-TIME SWORN PERSONNEL' /
   HIR_RTR_OTHR 'C9D.OTHER RETIREMENT PROGRAMS AVAILABLE TO FULL-TIME SWORN PERSONNEL' /
   HIR_RTR_SPEC 'C9TEXT.OTHER RETIREMENT PROGRAMS AVAILABLE TO FULL-TIME SWORN PERSONNEL - SPECIFIED' /
   HIR_SEP_NMED 'C10A.NUMBER OF FULL-TIME SWORN PERSONNEL SEPARATED DUE TO NON-MEDICAL RETIREMENT' /
   HIR_SEP_MED 'C10B.NUMBER OF FULL-TIME SWORN PERSONNEL SEPARATED DUE TO MEDICAL/DISABILITY RETIREMENT' /
   HIR_SEP_VOL 'C10C.NUMBER OF FULL-TIME SWORN PERSONNEL SEPARATED DUE TO VOLUNTARY RESIGNATION' /
   HIR_SEP_LAYOFF 'C10D.NUMBER OF FULL-TIME SWORN PERSONNEL SEPARATED DUE TO LAYOFF' /
   HIR_SEP_DIS 'C10E.NUMBER OF FULL-TIME SWORN PERSONNEL SEPARATED DUE TO DISMISSAL/TERMINATION' /
   HIR_SEP_OTHR 'C10F.NUMBER OF FULL-TIME SWORN PERSONNEL SEPARATED DUE TO OTHER REASONS' /
   HIR_SEP_TTL 'C10G.TOTAL FULL-TIME SWORN PERSONNEL SEPARATED' /
   HIR_SEPNS_LAYOFF 'C11A.NUMBER OF FULL-TIME NONSWORN PERSONNEL SEPARATED DUE TO LAYOFF' /
   HIR_SEPNS_OTHR 'C11B.NUMBER OF FULL-TIME NONSWORN PERSONNEL SEPARATED DUE TO OTHER SEPARATION REASONS' /
   HIR_SEPNS_TTL 'C11C.TOTAL PERSONNEL SEPARATED' /
   BDGT_MNTH 'D1.?FIRST MONTH OF FISCAL YEAR?' /
   BDGT_TTL  'D2.?TOTAL OPERATING BUDGET?' /
   BDGT_TTL_EST 'D2EST.TOTAL OPERATING BUDGET IS AN ESTIMATE' /
   BDGT_SRC_MNC 'D3A.FUNDING SOURCE(S) FOR OPERATING BUDGET INCLUDED ONE OR MORE MUNICIPAL GOVERNMENT(S)' /
   BDGT_SRC_CNTY 'D3B.FUNDING SOURCE(S) FOR OPERATING BUDGET INCLUDED ONE OR MORE COUNTY GOVERNMENT(S)' /
   BDGT_SRC_STATE 'D3C.FUNDING SOURCE(S) FOR OPERATING BUDGET INCLUDED ONE OR MORE STATE GOVERNMENT AGENCIES' /
   BDGT_SRC_FED 'D3D.FUNDING SOURCE(S) FOR OPERATING BUDGET INCLUDED ONE OR MORE FEDERAL GOVERNMENT AGENCIES' /
   BDGT_SRC_CONT 'D3E.FUNDING SOURCE(S) FOR OPERATING BUDGET INCLUDED PAYMENT FOR CONTRACTED LAW ENFORCEMENT SERVICES' /
   BDGT_SRC_ASST 'D3F.FUNDING SOURCE(S) FOR OPERATING BUDGET INCLUDED ASSET FORFEITURE PROGRAM' /
   BDGT_SRC_FEE 'D3G.FUNDING SOURCE(S) FOR OPERATING BUDGET INCLUDED USER FEES' /
   BDGT_SRC_OTHR 'D3H.OTHER FUNDING SOURCE(S) FOR OPERATING BUDGET' /
   BDGT_SRC_SPEC 'D3TEXT.OTHER FUNDING SOURCE(S) FOR OPERATING BUDGET - SPECIFIED' /
   BDGT_RED  'D4.AGENCY-WIDE REDUCTIONS IN BASE SALARY IMPLEMENTED' /
   BDGT_PCT_SW 'D5A.PERCENT CHANGE IN BASE SALARY FOR SWORN PERSONNEL' /
   BDGT_PCT_NSW 'D5B.PERCENT CHANGE IN BASE SALARY FOR NONSWORN PERSONNEL' /
   BDGT_FUR  'D6.EMPLOYEES FURLOUGHED' /
   BDGT_FUR2_SW10 'D7A1.NUMBER OF SWORN PERSONNEL FURLOUGHED - 2010' /
   BDGT_FUR2_SW11 'D7B2.NUMBER OF SWORN PERSONNEL FURLOUGHED - 2011?' /
   BDGT_FUR2_SW12 'D7B3.NUMBER OF SWORN PERSONNEL FURLOUGHED - 2012?' /
   BDGT_FUR2_NSW10 'D7B1.NUMBER OF NONSWORN PERSONNEL FURLOUGHED - 2010' /
   BDGT_FUR2_NSW11 'D7B2.NUMBER OF NONSWORN PERSONNEL FURLOUGHED - 2011' /
   BDGT_FUR2_NSW12 'D7B3.NUMBER OF NONSWORN PERSONNEL FURLOUGHED - 2012' /
   COM_MIS   'E1.COMMUNITY POLICING COMPONENT IN MISSION STATEMENT' /
   COM_TRN_REC 'E2A.AT LEAST 8 HOURS OF COMMUNITY POLICING TRAINING FOR RECRUITS' /
   COM_TRN_INSRV 'E2B.AT LEAST 8 HOURS OF IN-SERVICE COMMUNITY POLICING TRAINING' /
   COM_SARA  'E3.SARA-TYPE PROBLEM-SOLVING PROJECTS ACTIVELY ENCOURAGED' /
   COM_NSARA 'E4.NUMBER OF PATROL OFFICERS ENGAGED IN SARA-TYPE PROBLEM-SOLVING PROJECTS' /
   COM_COL   'E5.EVALUATION CRITERIA FOR PATROL OFFICERS INCLUDES COLLABORATIVE PROBLEM-SOLVING PROJECTS' /
   COM_PTNR  'E6.PROBLEM-SOLVING PARTNERSHIP OR WRITTEN AGREEMENT WITH LOCAL ORGANIZATION' /
   COM_BT    'E7.SAME PATROL OFFICERS REGULARLY ASSIGNED RESPONSIBILITY FOR AREAS OR BEATS' /
   COM_NBT   'E8.NUMBER OF PATROL OFFICERS REGULARLY GIVEN RESPONSIBILITY FOR AREAS OR BEATS' /
   COM_SURV  'E9.UTILIZED INFORMATION FROM COMMUNITY SURVEY' /
   TECH_TYP_GUN 'F1A.UTILIZED GUNSHOT DETECTION SYSTEMS' /
   TECH_TYP_LIC 'F1B.UTILIZED LICENSE PLATE READERS' /
   TECH_TYP_SMRT 'F1C.UTILIZED SMARTPHONES' /
   TECH_TYP_VPUB 'F1D.UTILIZED VIDEO SURVEILLANCE OF PUBLIC AREAS' /
   TECH_TYP_VVEH 'F1E.UTILIZED VIDEO CAMERAS IN PATROL VEHICLES' /
   TECH_TYP_VPAT 'F1F.UTILIZED VIDEO CAMERAS ON PATROL OFFICERS' /
   TECH_TYP_VWPN 'F1G.UTILIZED VIDEO CAMERAS ON WEAPONS' /
   TECH_TYP_VOTHR 'F1H.UTILIZED OTHER TYPES OF VIDEO CAMERAS' /
   TECH_EAC_MREC 'F2A.ELECTRONIC ACCESS TO MOTOR VEHICLE RECORDS FOR PATROL OFFICERS' /
   TECH_EAC_DREC 'F2B.ELECTRONIC ACCESS TO DRIVER LICENSE RECORDS FOR PATROL OFFICERS' /
   TECH_EAC_CRIM 'F2C.ELECTRONIC ACCESS TO CRIMINAL HISTORY FOR PATROL OFFICERS' /
   TECH_EAC_WARR 'F2D.ELECTRONIC ACCESS TO OUTSTANDING WARRANTS FOR PATROL OFFICERS' /
   TECH_EAC_PROT 'F2E.ELECTRONIC ACCESS TO PROTECTION ORDERS FOR PATROL OFFICERS' /
   TECH_EAC_ADRS 'F2F.ELECTRONIC ACCESS TO HISTORY AT ADDRESS FOR PATROL OFFICERS' /
   TECH_CIR  'F3.PRIMARY METHOD FOR SUBMITTING CRIMINAL INCIDENT REPORTS' /
   TECH_CIR_SPEC 'F3TEXT.CRIMINAL INCIDENT REPORT PRIMARILY SUBMITTED BY OTHER METHOD - SPECIFIED' /
   TECH_CRS  'F4.COMPUTERIZED RECORD SYSTEM MAINTAINED FOR CRIMINAL INCIDENTS' /
   TECH_CREC_INC 'F5A.COMPUTERIZED RECORDS OF INCIDENT-BASED STATISTICS MAINTAINED' /
   TECH_CREC_SUM 'F5B.COMPUTERIZED RECORDS OF SUMMARY STATISTICS MAINTAINED' /
   TECH_CREC_NAR 'F5C.COMPUTERIZED RECORDS OF OFFICER NARRATIVES MAINTAINED' /
   TECH_CREC_OTHR 'F5D.COMPUTERIZED RECORDS OF OTHER INFORMATION MAINTAINED' /
   TECH_CREC_SPEC 'F5DTEXT.COMPUTERIZED RECORDS OF OTHER INFORMATION MAINTAINED - SPECIFIED' /
   TECH_REC_NAR 'F6A.COMPUTERIZED RECORDS INCLUDE NARRATIVE DESCRIPTIONS OF OFFENSES' /
   TECH_REC_CODE 'F6B.COMPUTERIZED RECORDS INCLUDE OFFENSE CODES' /
   TECH_REC_STAT 'F6C.COMPUTERIZED RECORDS INCLUDE STATUTE OR MUNICIPAL OFFENSE CODES' /
   TECH_REC_VIC 'F6D.COMPUTERIZED RECORDS INCLUDE VICTIM CHARACTERISTICS' /
   TECH_REC_SUS 'F6E.COMPUTERIZED RECORDS INCLUDE SUSPECT CHARACTERISTICS' /
   TECH_REC_LOC 'F6F.COMPUTERIZED RECORDS INCLUDE OFFENSE LOCATION' /
   TECH_REC_GEO 'F6G.COMPUTERIZED RECORDS INCLUDE GEOCODED ADDRESS' /
   TECH_REC_DATE 'F6H.COMPUTERIZED RECORDS INCLUDE OFFENSE DATE AND TIME' /
   TECH_WHO_NO 'F7.NO RESEARCH OR STATISTICAL ANALYSES CONDUCTED USING COMPUTERIZED RECORDS' /
   TECH_WHO_STAFF 'F7A.RESEARCH OR STATISTICAL ANALYSES USING COMPUTERIZED RECORDS CONDUCTED BY AGENCY STAFF' /
   TECH_WHO_EXTR 'F7B.RESEARCH OR STATISTICAL ANALYSES USING COMPUTERIZED RECORDS CONDUCTED BY EXTERNAL ORGANIZATIONS' /
   TECH_MANY_FTS 'F8A.NUMBER OF SWORN PERSONNEL CONDUCTING RESEARCH OR STATISTICAL ANALYSES USING COMPUTERIZED RECORDS FULL-TIME' /
   TECH_MANY_PTS 'F8B.NUMBER OF SWORN PERSONNEL CONDUCTING RESEARCH OR STATISTICAL ANALYSES USING COMPUTERIZED RECORDS PART TIME' /
   TECH_MANY_FTNS 'F8C.NUMBER OF NONSWORN PERSONNEL CONDUCTING RESEARCH OR STATISTICAL ANALYSES USING COMPUTERIZED RECORDS FULL-TIME' /
   TECH_MANY_PTNS 'F8D.NUMBER OF NONSWORN PERSONNEL CONDUCTING RESEARCH OR STATISTICAL ANALYSES USING COMPUTERIZED RECORDS PART TIME' /
   TECH_OUT_LAW 'F9-1.RESEARCH OR STATISTICAL ANALYSES USING COMPUTERIZED RECORDS CONDUCTED BY OTHER LAW ENFORCEMENT AGENCY' /
   TECH_OUT_GOV 'F9-2.RESEARCH OR STATISTICAL ANALYSES USING COMPUTERIZED RECORDS CONDUCTED BY OTHER GOVERNMENT AGENCY' /
   TECH_OUT_UNIV 'F9-3.RESEARCH OR STATISTICAL ANALYSES USING COMPUTERIZED RECORDS CONDUCTED BY COLLEGE, UNIVERSITY, OR NON-PROFIT ORGANIZATION' /
   TECH_OUT_VEND 'F9-4.RESEARCH OR STATISTICAL ANALYSES USING COMPUTERIZED RECORDS CONDUCTED BY COMMERCIAL VENDOR' /
   TECH_OUT_OTHR 'F9-5.RESEARCH OR STATISTICAL ANALYSES USING COMPUTERIZED RECORDS CONDUCTED BY OTHER SOURCE' /
   TECH_OUT_OTHR_SPEC 'F9TEXT.OTHER SOURCE CONDUCTING RESEARCH OR STATISTICAL ANALYSES USING COMPUTERIZED - SPECIFIED' /
   TECH_WEB_NONE 'F10.NO AGENCY WEBSITE' /
   TECH_WEB_JUR 'F10A.JURISDICTION-WIDE SUMMARIES OF CRIME STATISTICS AVAILABLE TO PUBLIC THROUGH WEBSITE' /
   TECH_WEB_BEAT 'F10B.SUMMARIES OF CRIME STATISTICS BY BEAT, DISTRICT, OR OTHER AREA WITHIN JURISDICTION AVAILABLE TO PUBLIC THROUGH WEBSITE' /
   TECH_WEB_MAP 'F10C.STREET-LEVEL MAPS REPORTING LOCATION AND NATURE OF SPECIFIC CRIMES AVAILABLE TO PUBLIC THROUGH WEBSITE' /
   TECH_WEB_OFFND 'F10D.STREET-LEVEL MAPS REPORTING THE RESIDENTIAL LOCATION OF SEX OFFENDERS AVAILABLE TO PUBLIC THROUGH WEBSITE' /
   TECH_WEB_OTHR 'F10E.OTHER CRIME-RELATED INFORMATION AVAILABLE TO PUBLIC THROUGH WEBSITE' /
   TECH_WEB_SPEC 'F10ETEXT.OTHER CRIME-RELATED INFORMATION AVAILABLE TO PUBLIC THROUGH WEBSITE - SPECIFIED' /
   TECH_PUBL_REP 'F11A.CRIMES REPORTED BY PUBLIC THROUGH WEBSITE' /
   TECH_PUBL_ASK 'F11B.QUESTION ASKED BY PUBLIC THROUGH WEBSITE' /
   TECH_PUBL_FILE 'F11C.OFFICER OR AGENCY COMPLAINTS FILED BY PUBLIC THROUGH WEBSITE' /
   TECH_PUBL_OTHR 'F11D.OTHER INFORMATION PROVIDED BY PUBLIC THROUGH WEBSITE' /
   TECH_PUBL_SPEC 'F11DTEXT.OTHER INFORMATION PROVIDED BY PUBLIC THROUGH WEBSITE - SPECIFIED' /
   TECH_REPT 'F12.PUBLIC CAN REPORT CRIMES BY E-MAIL OR TEXTING' /
   TECH_RECV 'F13.PUBLIC CAN RECEIVE INFORMATION BY E-MAIL OR TEXTING' /
   TECH_MEDIA_TW 'F14A.AGENCY SOCIAL MEDIA USE INCLUDES TWITTER' /
   TECH_MEDIA_FB 'F14B.AGENCY SOCIAL MEDIA USE INCLUDES FACEBOOK' /
   TECH_MEDIA_BLOG 'F14C.AGENCY SOCIAL MEDIA USE INCLUDES BLOGS' /
   TECH_MEDIA_YTBE 'F14D.AGENCY SOCIAL MEDIA USE INCLUDES YOUTUBE OR SIMILAR VIDEO SHARING PROGRAM' /
   TECH_MEDIA_MASS 'F14E.AGENCY SOCIAL MEDIA USE INCLUDES MASS COMMUNICATION OR NOTIFICATION SYSTEM' /
   TECH_MEDIA_OTHR 'F14F.AGENCY SOCIAL MEDIA USE INCLUDES OTHER METHODS' /
   TECH_MEDIA_SPEC 'F14FTEXT.OTHER SOCIAL MEDIA METHODS USED BY AGENCY - SPECIFIED' /
   VEH_OPRT_MK 'G1A.NUMBER OF MARKED VEHICLES OPERATED' /
   VEH_OPRT_UNMK 'G1B.NUMBER OF UNMARKED VEHICLES OPERATED' /
   VEH_TYP_MTR 'G2A.MOTORCYCLE(S) OPERATED BY AGENCY' /
   VEH_TYP_ATV 'G2B.ATV(S) OPERATED BY AGENCY' /
   VEH_TYP_AIR 'G2C.AIRCRAFT OPERATED BY AGENCY' /
   VEH_TYP_HCOP 'G2D.HELICOPTER(S) OPERATED BY AGENCY' /
   VEH_TYP_BOAT 'G2E.BOAT(S) OPERATED BY AGENCY' /
   VEH_TYP_DRONE 'G2F.DRONE(S) OPERATED BY AGENCY' /
   VEH_TYP_OTHR 'G2G.OTHER VEHICLE TYPE(S) OPERATED BY AGENCY' /
   VEH_TYP_SPEC 'G2GTEXT.OTHER VEHICLE TYPE(S) OPERATED BY AGENCY - SPECIFIED' /
   VEH_WPUR  'G3.WRITTEN PURSUIT DRIVING POLICY' /
   VEH_WPUR_SPEC 'G3TEXT.OTHER RESTRICTIONS PLACED ON DRIVING PURSUIT - SPECIFIED' /
   VEH_DOC   'G4.VEHICLE PURSUIT INCIDENT DOCUMENTATION' /
   VEH_DOC_SPEC 'G4TEXT.OTHER METHOD DOCUMENTS PURSUIT INCIDENTS - SPECIFIED' /
   VEH_NPUR  'G5.NUMBER OF VEHICLE PURSUITS' /
   VEH_NPUR_EST 'G5EST.NUMBER OF VEHICLE PURSUITS ESTIMATED' /
   VEH_NPUR_UNK 'G5UNK.NUMBER OF VEHICLE PURSUITS UNKNOWN' /
   VEH_REST_NO 'G6.NO WRITTEN POLICY ON FOOT PURSUITS' /
   VEH_REST_ALN 'G6A.RESTRICTIONS APPLIED TO FOOT PURSUIT IF OFFICER ACTING ALONE' /
   VEH_REST_VISL 'G6B.RESTRICTIONS APPLIED TO FOOT PURSUIT IF OFFICER LOSES VISUAL CONTACT' /
   VEH_REST_SEPR 'G6C.RESTRICTIONS APPLIED TO FOOT PURSUIT IF OFFICERS SEPARATED' /
   VEH_REST_RADIO 'G6D.RESTRICTIONS APPLIED TO FOOT PURSUIT IF OFFICER LOSES RADIO CONTACT' /
   VEH_REST_ARM 'G6E.RESTRICTIONS APPLIED TO FOOT PURSUIT IF SUSPECT IS ARMED' /
   VEH_REST_OTHR 'G6F.OTHER RESTRICTIONS APPLIED TO FOOT PURSUIT' /
   VEH_REST_SPEC 'G6FTEXT.OTHER RESTRICTIONS APPLIED TO FOOT PURSUIT - SPECIFIED' /
   VEH_CNTN  'G7.WRITTEN FOOT PURSUIT POLICY ENCOURAGES THE USE OF CONTAINMENT TACTICS' /
   SAFE_AUTH_HGN 'H1A.HANDGUNS AUTHORIZED FOR USE BY SWORN FIELD/PATROL OFFICERS' /
   SAFE_AUTH_RFL 'H1B.RIFLE AUTHORIZED FOR USE BY SWORN FIELD/PATROL OFFICERS' /
   SAFE_AUTH_SGN 'H1C.SHOTGUN AUTHORIZED FOR USE BY SWORN FIELD/PATROL OFFICERS' /
   SAFE_AUTH_BTN 'H1D.BATONS AUTHORIZED FOR USE BY SWORN FIELD/PATROL OFFICERS' /
   SAFE_AUTH_IMP 'H1E.OTHER IMPACT WEAPONS AUTHORIZED FOR USE BY SWORN FIELD/PATROL OFFICERS' /
   SAFE_AUTH_SOFT 'H1F.SOFT PROJECTILES AUTHORIZED FOR USE BY SWORN FIELD/PATROL OFFICERS' /
   SAFE_AUTH_SPRAY 'H1G.OC SPRAY AUTHORIZED FOR USE BY SWORN FIELD/PATROL OFFICERS' /
   SAFE_AUTH_CHEM 'H1H.OTHER CHEMICAL AGENTS AUTHORIZED FOR USE BY SWORN FIELD/PATROL OFFICERS' /
   SAFE_AUTH_TASR 'H1I.TASERS AUTHORIZED FOR USE BY SWORN FIELD/PATROL OFFICERS' /
   SAFE_AUTH_NECK 'H1J.NECK RESTRAINTS AUTHORIZED FOR USE BY SWORN FIELD/PATROL OFFICERS' /
   SAFE_AUTH_TKDWN 'H1K.TAKEDOWN TECHNIQUES AUTHORIZED FOR USE BY SWORN FIELD/PATROL OFFICERS' /
   SAFE_AUTH_OHAND 'H1L.OPEN-HAND TECHNIQUES AUTHORIZED FOR USE BY SWORN FIELD/PATROL OFFICERS' /
   SAFE_AUTH_CHAND 'H1M.CLOSED-HAND TECHNIQUES AUTHORIZED FOR USE BY SWORN FIELD/PATROL OFFICERS' /
   SAFE_AUTH_LEG 'H1N.LEG HOBBLE OR OTHER SEVERE RESTRAINTS AUTHORIZED FOR USE BY SWORN FIELD/PATROL OFFICERS' /
   SAFE_DOC_DISF 'H2A.DOCUMENTATION REQUIRED FOR DISPLAY OF FIREARM' /
   SAFE_DOC_DCHF 'H2B.DOCUMENTATION REQUIRED FOR DISCHARGE FIREARM' /
   SAFE_DOC_BAT 'H2C.DOCUMENTATION REQUIRED FOR BATON USE' /
   SAFE_DOC_IMP 'H2D.DOCUMENTATION REQUIRED FOR OTHER IMPACT WEAPON USE' /
   SAFE_DOC_SOFT 'H2E.DOCUMENTATION REQUIRED FOR SOFT PROJECTILE USE' /
   SAFE_DOC_SPRAY 'H2F.DOCUMENTATION REQUIRED FOR OC SPRAY USE' /
   SAFE_DOC_CHEM 'H2G.DOCUMENTATION REQUIRED FOR OTHER CHEMICAL AGENT USE' /
   SAFE_DOC_DIST 'H2H.DOCUMENTATION REQUIRED FOR DISPLAY OF TASER' /
   SAFE_DOC_DCHT 'H2I.DOCUMENTATION REQUIRED FOR DISCHARGE OF TASER' /
   SAFE_DOC_NECK 'H2J.DOCUMENTATION REQUIRED FOR NECK RESTRAINTS USE' /
   SAFE_DOC_TKDWN 'H2K.DOCUMENTATION REQUIRED FOR TAKEDOWN TECHNIQUE USE' /
   SAFE_DOC_OHAND 'H2L.DOCUMENTATION REQUIRED FOR OPEN-HAND TECHNIQUE USE' /
   SAFE_DOC_CHAND 'H2M.DOCUMENTATION REQUIRED FOR CLOSED-HAND TECHNIQUE USE' /
   SAFE_DOC_LEG 'H2N.DOCUMENTATION REQUIRED FOR LEG HOBBLE OR OTHER SEVERE RESTRAINT USE' /
   SAFE_FINC 'H3.DOCUMENTATION OF USE OF FORCE' /
   SAFE_FINC_SPEC 'H3CTEXT.OTHER DOCUMENTATION FOR USE OF FORCE - SPECIFIED' /
   NO_RECORD_FORCE 'H4.NO RECORD OF USES OF FORCE' /
   SAFE_FRC_INC 'H4A.ONE REPORT PER USE OF FORCE INCIDENT' /
   SAFE_FRC_OFFC 'H4B.ONE REPORT PER OFFICER INVOLVED IN USE OF FORCE INCIDENT' /
   SAFE_FRC_OTHR 'H4C.OTHER METHOD TO RECORD USE OF FORCE INCIDENTS' /
   SAFE_FRC_SPEC 'H4CTEXT.OTHER METHOD TO RECORD USE OF FORCE INCIDENTS - SPECIFIED' /
   SAFE_FTTL 'H5.NUMBER OF USE OF FORCE INCIDENTS' /
   SAFE_FTTL_EST 'H5EST.NUMBER OF USE OF FORCE INCIDENTS IS AN ESTIMATE' /
   SAFE_FTTL_UNK 'H5UNK.NUMBER OF USE OF FORCE INCIDENTS UNKNOWN' /
   SAFE_SEPR 'H6.NUMBER OF SEPARATE REPORTS OF USE OF FORCE INCIDENTS FROM INDIVIDUAL OFFICERS' /
   SAFE_SEPR_EST 'H6EST.NUMBER OF SEPARATE REPORTS OF USE OF FORCE INCIDENTS FROM INDIVIDUAL OFFICERS IS AN ESTIMATE' /
   SAFE_SEPR_UNK 'H6UNK.NUMBER OF SEPARATE REPORTS OF USE OF FORCE INCIDENTS FROM INDIVIDUAL OFFICERS UNKNOWN' /
   SAFE_ARMR 'H7.BODY ARMOR SELECTION POLICY FOR SWORN PERSONNEL' /
   SAFE_ARMR_OTHRS 'H7TEXT.OTHER SELECTION POLICY FOR BODY ARMOR - SPECIFIED' /
   SAFE_RQUR_ACC 'H8A.REQUIRED ACCESS TO BODY ARMOR FOR UNIFORMED FIELD/PATROL OFFICERS AT ALL TIMES' /
   SAFE_RQUR_RSK 'H8B.UNIFORMED FIELD/PATROL OFFICERS REQUIRED TO WEAR BODY ARMOR IN HIGH RISK CONDITIONS' /
   SAFE_RQUR_ALL 'H8C.UNIFORMED FIELD/PATROL OFFICERS REQUIRED TO WEAR BODY ARMOR AT ALL TIMES' /
   SAFE_RQUR_CSTM 'H8D.BODY ARMOR REQUIRED TO BE CUSTOM FITTED TO OFFICER' /
   SAFE_RQUR_TRN 'H8E.OFFICERS REQUIRED TO BE TRAINED FOR PROPER WEAR' /
   SAFE_RQUR_COMP 'H8F.SUPERVISORS REQUIRED TO INSPECT PERSONNEL FOR COMPLIANCE WITH BODY ARMOR POLICY' /
   SAFE_RQUR_BLST 'H8G.BODY ARMOR REQUIRED TO BE PURCHASED IN COMPLIANCE WITH NIJ BALLISTIC-RESISTANT STANDARD' /
   NO_BODY_ARMOR 'H9.AGENCY DOES NOT USE BODY ARMOR' /
   SAFE_PAY_DPT 'H9A.BODY ARMOR PAID FOR BY DEPARTMENT' /
   SAFE_PAY_IND 'H9B.BODY ARMOR PAID FOR BY INDIVIDUAL OFFICER' /
   SAFE_PAY_GRNT 'H9C.BODY ARMOR PAID FOR BY GRANTS' /
   SAFE_PAY_OTHR 'H9D.BODY ARMOR PAID FOR BY OTHER SOURCE(S)' /
   SAFE_PAY_SPEC 'H9TEXT.BODY ARMOR PAID FOR BY OTHER SOURCE(S) - SPECIFIED' /
   ISSU_ADDR_BIAS 'I1A.SPECIALIZED UNIT FOR BIAS/HATE CRIME' /
   ISSU_ADDR_BOMB 'I1B.SPECIALIZED UNIT FOR BOMB/EXPLOSIVE DISPOSAL' /
   ISSU_ADDR_ABSE 'I1C.SPECIALIZED UNIT FOR CHILD ABUSE' /
   ISSU_ADDR_CYBR 'I1D.SPECIALIZED UNIT FOR CYBERCRIME' /
   ISSU_ADDR_DPV 'I1E.SPECIALIZED UNIT FOR DOMESTIC PARTNER VIOLENCE' /
   ISSU_ADDR_TERR 'I1F.SPECIALIZED UNIT FOR TERRORISM' /
   ISSU_ADDR_TRAF 'I1G.SPECIALIZED UNIT FOR HUMAN TRAFFICKING' /
   ISSU_ADDR_DUI 'I1H.SPECIALIZED UNIT FOR IMPAIRED DRIVING' /
   ISSU_ADDR_JUV 'I1I.SPECIALIZED UNIT FOR JUVENILE CRIME' /
   ISSU_ADDR_GANG 'I1J.SPECIALIZED UNIT FOR GANGS' /
   ISSU_ADDR_REEN 'I1K.SPECIALIZED UNIT FOR RE-ENTRY SURVEILLANCE' /
   ISSU_ADDR_FUG 'I1L.SPECIALIZED UNIT FOR FUGITIVES' /
   ISSU_ADDR_VIC 'I1M.SPECIALIZED UNIT FOR VICTIM ASSISTANCE' /
   ISSU_ADDR_SWAT 'I1N.SPECIALIZED UNIT FOR SPECIAL OPERATIONS' /
   ISSU_SPEC 'I2.NUMBER OF SPECIALIZED UNITS' /
   ISSU_MULTI 'I3.AGENCY PARTICIPATES IN MULTIJURISDICTIONAL TASK FORCES' /
   ISSU_TASK_SWAT 'I4A.MULTIJURISDICTIONAL TASK FORCE FOR SPECIAL OPERATIONS' /
   ISSU_TASK_DRUG 'I4B.MULTIJURISDICTIONAL TASK FORCE FOR DRUGS' /
   ISSU_TASK_GANG 'I4C.MULTIJURISDICTIONAL TASK FORCE FOR GANGS' /
   ISSU_TASK_TRAF 'I4D.MULTIJURISDICTIONAL TASK FORCE FOR HUMAN TRAFFICKING' /
   ISSU_TASK_OTHR 'I4E.MULTIJURISDICTIONAL TASK FORCE FOR OTHER CRIMES' /
   ISSU_TASK_SPEC 'I4TEXT.MULTIJURISDICTIONAL TASK FORCE FOR OTHER CRIMES - SPECIFIED' /
   BASEWT    'BASE SAMPLING WEIGHT FOR EACH STRATUM' /
   NRADJUST  'NON-RESPONSE ADJUSTMENT FOR STRATUM' /
   FINALWT   'FINAL WEIGHT FOR EACH STRATUM' /
   .


* SPSS VALUE LABELS COMMAND.

VALUE LABELS
   SHERIFF_FLAG 0 'LEMAS - no research needed' 1 'UCR' 2 'Code not used'
             3 'LEMAS - confirmed' 4 'CSLLEA' 5 'Both LEMAS and UCR' /
   TYPE      '1' 'Local police department' '2' 'Sheriff''s office'
             '3' 'Primary state LE' /
   TRIBALPD  1 'Tribal-operated' 2 'Not tribal' /
   COUNTYPD  1 'County PD' 2 'Not county operated' /
   STRATCODE 101 'Local PD - SR' 102 'Local PD - 50 to 99'
             103 'Local PD - 25 to 49' 104 'Local PD - 10 to 24'
             105 'Local PD - 5 to 9' 106 'Local PD - 2 to 4'
             107 'Local PD - 1 FT officer' 201 'Sheriff - SR'
             202 'Sheriff- 50 to 99' 203 'Sheriff- 25 to 49'
             204 'Sheriff- 10 to 24' 205 'Sheriff- 5 to 9'
             206 'Sheriff- 2 to 4' 207 'Sheriff- 1 FT officer'
             301 'State LE - SR' /
   FTSWORN   -9 'Unknown/does not know' /
   FTCIV     -9 'Unknown/does not know' /
   PTSWORN   -9 'Unknown/does not know' /
   PTCIV     -9 'Unknown/does not know' /
   PERS_PDSW_MFT -9 'Unknown/does not know' /
   PERS_PDSW_MPT -9 'Unknown/does not know' /
   PERS_PDSW_FFT -9 'Unknown/does not know' /
   PERS_PDSW_FPT -9 'Unknown/does not know' /
   PERS_FTS_WHT -9 'Unknown/does not know' /
   PERS_FTS_BLK -9 'Unknown/does not know' /
   PERS_FTS_HSP -9 'Unknown/does not know' /
   PERS_FTS_IND -9 'Unknown/does not know' /
   PERS_FTS_ASN -9 'Unknown/does not know' /
   PERS_FTS_HAW -9 'Unknown/does not know' /
   PERS_FTS_TWO -9 'Unknown/does not know' /
   PERS_FTS_UNK -9 'Unknown/does not know' /
   PERS_FTS_RACETOT -9 'Unknown/does not know' /
   PERS_RESP_PATRL -9 'Unknown/does not know' /
   PERS_RESP_INVST -9 'Unknown/does not know' /
   PERS_RESP_JAIL -9 'Unknown/does not know' -8 'Not applicable' /
   PERS_RESP_CRT -9 'Unknown/does not know' /
   PERS_RESP_OTHR -9 'Unknown/does not know' -8 'Not applicable' /
   PERS_SUP_CHF_M -9 'Unknown/does not know' /
   PERS_SUP_CHF_F -9 'Unknown/does not know' /
   PERS_SUP_INTM_M -9 'Unknown/does not know' -8 'Not applicable' /
   PERS_SUP_INTM_F -9 'Unknown/does not know' -8 'Not applicable' /
   PERS_SUP_SGT_M -9 'Unknown/does not know' -8 'Not applicable' /
   PERS_SUP_SGT_F -9 'Unknown/does not know' -8 'Not applicable' /
   PERS_SSW_FT -9 'Unknown/does not know' /
   PERS_SSW_PT -9 'Unknown/does not know' /
   PERS_UPSW -9 'Unknown/does not know' /
   PERS_DUT_NONE -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PERS_DUT_ADMN -9 'Unknown/does not know'
             -8 'Not applicable (Agency does not employ nonsworn personnel)'
             1 'Yes' 2 'No' /
   PERS_DUT_CLN -9 'Unknown/does not know'
             -8 'Not applicable (Agency does not employ nonsworn personnel)'
             1 'Yes' 2 'No' /
   PERS_DUT_LGL -9 'Unknown/does not know'
             -8 'Not applicable (Agency does not employ nonsworn personnel)'
             1 'Yes' 2 'No' /
   PERS_DUT_ACCT -9 'Unknown/does not know'
             -8 'Not applicable (Agency does not employ nonsworn personnel)'
             1 'Yes' 2 'No' /
   PERS_DUT_FSCI -9 'Unknown/does not know'
             -8 'Not applicable (Agency does not employ nonsworn personnel)'
             1 'Yes' 2 'No' /
   PERS_DUT_RSRCH -9 'Unknown/does not know'
             -8 'Not applicable (Agency does not employ nonsworn personnel)'
             1 'Yes' 2 'No' /
   PERS_DUT_HR -9 'Unknown/does not know'
             -8 'Not applicable (Agency does not employ nonsworn personnel)'
             1 'Yes' 2 'No' /
   PERS_DUT_IT -9 'Unknown/does not know'
             -8 'Not applicable (Agency does not employ nonsworn personnel)'
             1 'Yes' 2 'No' /
   PERS_DUT_VM -9 'Unknown/does not know'
             -8 'Not applicable (Agency does not employ nonsworn personnel)'
             1 'Yes' 2 'No' /
   PERS_DUT_CD -9 'Unknown/does not know'
             -8 'Not applicable (Agency does not employ nonsworn personnel)'
             1 'Yes' 2 'No' /
   PERS_DUT_CRT -9 'Unknown/does not know'
             -8 'Not applicable (Agency does not employ nonsworn personnel)'
             1 'Yes' 2 'No' /
   PERS_DUT_JAIL -9 'Unknown/does not know'
             -8 'Not applicable (Agency does not employ nonsworn personnel)'
             1 'Yes' 2 'No' /
   PERS_DUT_OTHR -9 'Unknown/does not know'
             -8 'Not applicable (Agency does not employ nonsworn personnel)'
             1 'Yes' 2 'No' /
   PAY_SAL_EXC_MIN -9 'Unknown/does not know' -8 'Not applicable' /
   PAY_SAL_EXC_MAX -9 'Unknown/does not know' -8 'Not applicable' /
   PAY_SAL_SGT_MIN -9 'Unknown/does not know' -8 'Not applicable' /
   PAY_SAL_SGT_MAX -9 'Unknown/does not know' -8 'Not applicable' /
   PAY_SAL_OFCR_MIN -9 'Unknown/does not know' -8 'Not applicable' /
   PAY_SAL_OFCR_MAX -9 'Unknown/does not know' -8 'Not applicable' /
   PAY_INCT_EDU -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PAY_INCT_VOC -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PAY_INCT_LANG -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PAY_INCT_SPCL -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PAY_INCT_HZRD -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PAY_INCT_SD -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PAY_INCT_RINC -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PAY_INCT_MRT -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PAY_INCT_OTHR -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PAY_OUT   -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PAY_RST_NO -9 'Unknown/does not know'
             -8 'Not applicable (No sworn personnel can work outside agency)'
             1 'Yes' 2 'No' /
   PAY_RST_HRS -9 'Unknown/does not know'
             -8 'Not applicable (No sworn personnel can work outside agency)'
             1 'Yes' 2 'No' /
   PAY_RST_TYPE -9 'Unknown/does not know'
             -8 'Not applicable (No sworn personnel can work outside agency)'
             1 'Yes' 2 'No' /
   PAY_RST_OTHR -9 'Unknown/does not know'
             -8 'Not applicable (No sworn personnel can work outside agency)'
             1 'Yes' 2 'No' /
   PAY_BARG  -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PAY_SBARG -9 'Unknown/does not know'
             -8 'Not applicable (No collective bargaining organization'
             1 'Active' 2 'Expired' 3 'No collective bargaining agreement' /
   PAY_RMB_TUIT -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PAY_RMB_UNF -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PAY_RMB_ARMR -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PAY_RMB_SFTY -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PAY_RMB_FIRE -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PAY_OVER_SW -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PAY_OVER_NSW -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PAY_FUNC_CRT -9 'Unknown/does not know'
           -8 'Not applicable (No overtime compensation for sworn personnel)'
             1 'Yes' 2 'No' /
   PAY_FUNC_SHFT -9 'Unknown/does not know'
           -8 'Not applicable (No overtime compensation for sworn personnel)'
             1 'Yes' 2 'No' /
   PAY_FUNC_PTRL -9 'Unknown/does not know'
           -8 'Not applicable (No overtime compensation for sworn personnel)'
             1 'Yes' 2 'No' /
   PAY_FUNC_INVS -9 'Unknown/does not know'
           -8 'Not applicable (No overtime compensation for sworn personnel)'
             1 'Yes' 2 'No' /
   PAY_FUNC_ADMN -9 'Unknown/does not know'
           -8 'Not applicable (No overtime compensation for sworn personnel)'
             1 'Yes' 2 'No' /
   PAY_FUNC_EMRG -9 'Unknown/does not know'
           -8 'Not applicable (No overtime compensation for sworn personnel)'
             1 'Yes' 2 'No' /
   PAY_FUNC_EVNT -9 'Unknown/does not know'
           -8 'Not applicable (No overtime compensation for sworn personnel)'
             1 'Yes' 2 'No' /
   PAY_FUNC_OTHR -9 'Unknown/does not know'
           -8 'Not applicable (No overtime compensation for sworn personnel)'
             1 'Yes' 2 'No' /
   PAY_LMT   -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   PAY_VEH_MRK -9 'Unknown/does not know' 1 'All sworn' 2 'Some sworn'
             3 'Not authorized' /
   PAY_VEH_UMRK -9 'Unknown/does not know' 1 'All sworn' 2 'Some sworn'
             3 'Not authorized' /
   HIR_FRZ   -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   HIR_MTH_SW10 -9 'Unknown/does not know'
             -8 'Not applicable (No hiring freeze)' /
   HIR_MTH_SW11 -9 'Unknown/does not know'
             -8 'Not applicable (No hiring freeze)' /
   HIR_MTH_SW12 -9 'Unknown/does not know'
             -8 'Not applicable (No hiring freeze)' /
   HIR_MTH_NSW10 -9 'Unknown/does not know'
             -8 'Not applicable (No hiring freeze)' /
   HIR_MTH_NSW11 -9 'Unknown/does not know'
             -8 'Not applicable (No hiring freeze)' /
   HIR_MTH_NSW12 -9 'Unknown/does not know'
             -8 'Not applicable (No hiring freeze)' /
   HIR_NBR   -9 'Unknown/does not know' 1 'Yes - none' 2 'No' /
   HIR_NBR_DRCT_FT -9 'Unknown/does not know'
             -8 'Not applicable (No sworn personnel hired)' /
   HIR_NBR_DRCT_PT -9 'Unknown/does not know'
             -8 'Not applicable (No sworn personnel hired)' /
   HIR_NBR_PRE_FT -9 'Unknown/does not know'
             -8 'Not applicable (No sworn personnel hired)' /
   HIR_NBR_PRE_PT -9 'Unknown/does not know'
             -8 'Not applicable (No sworn personnel hired)' /
   HIR_NBR_LAT_FT -9 'Unknown/does not know'
             -8 'Not applicable (No sworn personnel hired)' /
   HIR_NBR_LAT_PT -9 'Unknown/does not know'
             -8 'Not applicable (No sworn personnel hired)' /
   HIR_NBR_TFT -9 'Unknown/does not know'
             -8 'Not applicable (No sworn personnel hired)' /
   HIR_NBR_TPT -9 'Unknown/does not know'
             -8 'Not applicable (No sworn personnel hired)' /
   HIR_TRN_NO_L -9 'Unknown/does not know' 1 'Yes - none' 2 'No' /
   HIR_TRN_NO_P -9 'Unknown/does not know' 1 'Yes - none' 2 'No' /
   HIR_TRN_CRS_L -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   HIR_TRN_CRS_P -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   HIR_TRN_FLD_L -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   HIR_TRN_FLD_P -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   HIR_TRN_DIR_L -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   HIR_TRN_DIR_P -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   HIR_NSWT_NO -9 'Unknown/does not know' 1 'Yes - none' 2 'No' /
   HIR_NSWT_VAR_FT -9 'Unknown/does not know'
             -8 'Not applicable (No nonsworn were hired)' /
   HIR_NSWT_VAR_PT -9 'Unknown/does not know'
             -8 'Not applicable (No nonsworn were hired)' /
   HIR_EDU_NO -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   HIR_EDU_HS -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   HIR_EDU_SCOL -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   HIR_EDU_AD -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   HIR_EDU_BD -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   HIR_EDU_OTHR -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   HIR_MIL   -9 'Unknown/does not know' -8 'Not applicable' 1 'Yes' 2 'No' /
   HIR_BD_VAR -9 'Unknown/does not know' -8 'Not applicable' /
   HIR_RTR_DB -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   HIR_RTR_DC -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   HIR_RTR_SS -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   HIR_RTR_OTHR -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   HIR_SEP_NMED -9 'Unknown/does not know' /
   HIR_SEP_MED -9 'Unknown/does not know' /
   HIR_SEP_VOL -9 'Unknown/does not know' /
   HIR_SEP_LAYOFF -9 'Unknown/does not know' /
   HIR_SEP_DIS -9 'Unknown/does not know' /
   HIR_SEP_OTHR -9 'Unknown/does not know' /
   HIR_SEP_TTL -9 'Unknown/does not know' /
   HIR_SEPNS_LAYOFF -9 'Unknown/does not know' /
   HIR_SEPNS_OTHR -9 'Unknown/does not know' /
   HIR_SEPNS_TTL -9 'Unknown/does not know' /
   BDGT_MNTH -9 'Unknown/does not know' 1 'January' 2 'February' 3 'March'
             4 'April' 5 'May' 6 'June' 7 'July' 8 'August' 9 'September'
             10 'October' 11 'November' 12 'December' /
   BDGT_TTL  -9 'Unknown/does not know' /
   BDGT_TTL_EST 1 'Yes' 2 'No' /
   BDGT_SRC_MNC -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   BDGT_SRC_CNTY -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   BDGT_SRC_STATE -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   BDGT_SRC_FED -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   BDGT_SRC_CONT -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   BDGT_SRC_ASST -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   BDGT_SRC_FEE -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   BDGT_SRC_OTHR -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   BDGT_RED  -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   BDGT_PCT_SW -9 'Unknown/does not know'
             -8 'Not applicable (No agency-wide reductions in salary)' /
   BDGT_PCT_NSW -9 'Unknown/does not know'
             -8 'Not applicable (No agency-wide reductions in salary)' /
   BDGT_FUR  -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   BDGT_FUR2_SW10 -9 'Unknown/does not know'
             -8 'Not applicable (No paid personnel furloughed)' /
   BDGT_FUR2_SW11 -9 'Unknown/does not know'
             -8 'Not applicable (No paid personnel furloughed)' /
   BDGT_FUR2_SW12 -9 'Unknown/does not know'
             -8 'Not applicable (No paid personnel furloughed)' /
   BDGT_FUR2_NSW10 -9 'Unknown/does not know'
             -8 'Not applicable (No paid personnel furloughed)' /
   BDGT_FUR2_NSW11 -9 'Unknown/does not know'
             -8 'Not applicable (No paid personnel furloughed)' /
   BDGT_FUR2_NSW12 -9 'Unknown/does not know'
             -8 'Not applicable (No paid personnel furloughed)' /
   COM_MIS   -9 'Unknown/does not know' 1 'No written mission statement'
             2 'Written statement, no community policing component'
             3 'Written statement, yes community policing component' /
   COM_TRN_REC -9 'Unknown/respondent does not know' -8 'Not applicable'
             1 'All' 2 'Half or more' 3 'Less than half' 4 'None' /
   COM_TRN_INSRV -9 'Unknown/respondent does not know' -8 'Not applicable'
             1 'All' 2 'Half or more' 3 'Less than half' 4 'None' /
   COM_SARA  -9 'Unknown/does not know' -8 'Not applicable' 1 'Yes' 2 'No' /
   COM_NSARA -9 'Unknown/respondent does not know'
 -8 'Not applicable (did not encourage SARA-type problem-solving projects participation)'
             /
   COM_COL   -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   COM_PTNR  -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   COM_BT    -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   COM_NBT   -9 'Unknown/respondent does not know'
             -8 'Not applicable (did not assign same areas or beats)' /
   COM_SURV  -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_TYP_GUN -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_TYP_LIC -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_TYP_SMRT -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_TYP_VPUB -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_TYP_VVEH -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_TYP_VPAT -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_TYP_VWPN -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_TYP_VOTHR -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_EAC_MREC -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_EAC_DREC -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_EAC_CRIM -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_EAC_WARR -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_EAC_PROT -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_EAC_ADRS -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_CIR  -9 'Unknown/does not know' 1 'Paper report'
             2 'Voice transmission' 3 'Smartphone' 4 'Computer' 5 'Other' /
   TECH_CRS  -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_CREC_INC -9 'Unknown/respondent does not know'
             -8 'Not applicable (No computerized records system)' 1 'Yes'
             2 'No' /
   TECH_CREC_SUM -9 'Unknown/respondent does not know'
             -8 'Not applicable (No computerized records system)' 1 'Yes'
             2 'No' /
   TECH_CREC_NAR -9 'Unknown/respondent does not know'
             -8 'Not applicable (No computerized records system)' 1 'Yes'
             2 'No' /
   TECH_CREC_OTHR -9 'Unknown/respondent does not know'
             -8 'Not applicable (No computerized records system)' 1 'Yes'
             2 'No' /
   TECH_REC_NAR -9 'Unknown/respondent does not know'
             -8 'Not applicable (No computerized records system)' 1 'Yes'
             2 'No' /
   TECH_REC_CODE -9 'Unknown/respondent does not know'
             -8 'Not applicable (No computerized records system)' 1 'Yes'
             2 'No' /
   TECH_REC_STAT -9 'Unknown/respondent does not know'
             -8 'Not applicable (No computerized records system)' 1 'Yes'
             2 'No' /
   TECH_REC_VIC -9 'Unknown/respondent does not know'
             -8 'Not applicable (No computerized records system)' 1 'Yes'
             2 'No' /
   TECH_REC_SUS -9 'Unknown/respondent does not know'
             -8 'Not applicable (No computerized records system)' 1 'Yes'
             2 'No' /
   TECH_REC_LOC -9 'Unknown/respondent does not know'
             -8 'Not applicable (No computerized records system)' 1 'Yes'
             2 'No' /
   TECH_REC_GEO -9 'Unknown/respondent does not know'
             -8 'Not applicable (No computerized records system)' 1 'Yes'
             2 'No' /
   TECH_REC_DATE -9 'Unknown/respondent does not know'
             -8 'Not applicable (No computerized records system)' 1 'Yes'
             2 'No' /
   TECH_WHO_NO -9 'Unknown/does not know' 1 'Yes-none' 2 'No' /
   TECH_WHO_STAFF -9 'Unknown/respondent does not know'
 -8 'Not applicable (No computerized records system or no analyses conducted)'
             1 'Yes' 2 'No' /
   TECH_WHO_EXTR -9 'Unknown/respondent does not know'
 -8 'Not applicable (No computerized records system or no analyses conducted)'
             1 'Yes' 2 'No' /
   TECH_MANY_FTS -9 'Unknown/respondent does not know'
 -8 'Not applicable (No computerized records system or no analyses conducted)'
             /
   TECH_MANY_PTS -9 'Unknown/respondent does not know'
 -8 'Not applicable (No computerized records system or no analyses conducted)'
             /
   TECH_MANY_FTNS -9 'Unknown/respondent does not know'
 -8 'Not applicable (No computerized records system or no analyses conducted)'
             /
   TECH_MANY_PTNS -9 'Unknown/respondent does not know'
 -8 'Not applicable (No computerized records system or no analyses conducted)'
             /
   TECH_OUT_LAW -9 'Unknown/respondent does not know'
 -8 'Not applicable (No computerized records system or no analyses conducted)'
             1 'Yes' 2 'No' /
   TECH_OUT_GOV -9 'Unknown/respondent does not know'
 -8 'Not applicable (No computerized records system or no analyses conducted)'
             1 'Yes' 2 'No' /
   TECH_OUT_UNIV -9 'Unknown/respondent does not know'
 -8 'Not applicable (No computerized records system or no analyses conducted)'
             1 'Yes' 2 'No' /
   TECH_OUT_VEND -9 'Unknown/respondent does not know'
 -8 'Not applicable (No computerized records system or no analyses conducted)'
             1 'Yes' 2 'No' /
   TECH_OUT_OTHR -9 'Unknown/respondent does not know'
 -8 'Not applicable (No computerized records system or no analyses conducted)'
             1 'Yes' 2 'No' /
   TECH_WEB_NONE -9 'Unknown/respondent does not know'
             -8 'Not applicable (Agency has no website)' 1 'Yes-none' 2 'No'
             /
   TECH_WEB_JUR -9 'Unknown/respondent does not know'
             -8 'Not applicable (Agency has no website)' 1 'Yes' 2 'No' /
   TECH_WEB_BEAT -9 'Unknown/respondent does not know'
             -8 'Not applicable (Agency has no website)' 1 'Yes' 2 'No' /
   TECH_WEB_MAP -9 'Unknown/respondent does not know'
             -8 'Not applicable (Agency has no website)' 1 'Yes' 2 'No' /
   TECH_WEB_OFFND -9 'Unknown/respondent does not know'
             -8 'Not applicable (Agency has no website)' 1 'Yes' 2 'No' /
   TECH_WEB_OTHR -9 'Unknown/respondent does not know'
             -8 'Not applicable (Agency has no website)' 1 'Yes' 2 'No' /
   TECH_PUBL_REP -9 'Unknown/respondent does not know'
             -8 'Not applicable (Agency has no website)' 1 'Yes' 2 'No' /
   TECH_PUBL_ASK -9 'Unknown/respondent does not know'
             -8 'Not applicable (Agency has no website)' 1 'Yes' 2 'No' /
   TECH_PUBL_FILE -9 'Unknown/respondent does not know'
             -8 'Not applicable (Agency has no website)' 1 'Yes' 2 'No' /
   TECH_PUBL_OTHR -9 'Unknown/respondent does not know'
             -8 'Not applicable (Agency has no website)' 1 'Yes' 2 'No' /
   TECH_REPT -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_RECV -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_MEDIA_TW -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_MEDIA_FB -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_MEDIA_BLOG -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_MEDIA_YTBE -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_MEDIA_MASS -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   TECH_MEDIA_OTHR -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   VEH_OPRT_MK -9 'Unknown/does not know' /
   VEH_OPRT_UNMK -9 'Unknown/does not know' /
   VEH_TYP_MTR -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   VEH_TYP_ATV -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   VEH_TYP_AIR -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   VEH_TYP_HCOP -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   VEH_TYP_BOAT -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   VEH_TYP_DRONE -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   VEH_TYP_OTHR -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   VEH_WPUR  -9 'Unknown/does not know' 1 'No written policy'
             2 'Permitted- officer discretion' 3 'Permitted- restricted'
             4 'Permitted- subject to review' 5 'Discouraged' 6 'Prohibited'
             7 'Other' /
   VEH_DOC   -9 'Unknown/does not know' 1 'No formal record'
             2 'Separate report' 3 'Use of force form'
             4 'Offense or arrest report' 5 'Other' /
   VEH_NPUR  -9 'Unknown/respondent does not know' /
   VEH_NPUR_EST 1 'Yes-estimated' 2 'No' /
   VEH_NPUR_UNK 1 'Yes-unknown' 2 'No' /
   VEH_REST_NO 1 'Yes-none' 2 'No' /
   VEH_REST_ALN -8 'Not applicable (No written foot pursuit policy)' 1 'Yes'
             2 'No' /
   VEH_REST_VISL -8 'Not applicable (No written foot pursuit policy)' 1 'Yes'
             2 'No' /
   VEH_REST_SEPR -8 'Not applicable (No written foot pursuit policy)' 1 'Yes'
             2 'No' /
   VEH_REST_RADIO -8 'Not applicable (No written foot pursuit policy)'
             1 'Yes' 2 'No' /
   VEH_REST_ARM -8 'Not applicable (No written foot pursuit policy)' 1 'Yes'
             2 'No' /
   VEH_REST_OTHR -8 'Not applicable (No written foot pursuit policy)' 1 'Yes'
             2 'No' /
   VEH_CNTN  -8 'Not applicable (No written foot pursuit policy)' 1 'Yes'
             2 'No' /
   SAFE_AUTH_HGN -9 'Unknown/does not know' 1 'All sworn' 2 'Some sworn'
             3 'Not authorized' /
   SAFE_AUTH_RFL -9 'Unknown/does not know' 1 'All sworn' 2 'Some sworn'
             3 'Not authorized' /
   SAFE_AUTH_SGN -9 'Unknown/does not know' 1 'All sworn' 2 'Some sworn'
             3 'Not authorized' /
   SAFE_AUTH_BTN -9 'Unknown/does not know' 1 'All sworn' 2 'Some sworn'
             3 'Not authorized' /
   SAFE_AUTH_IMP -9 'Unknown/does not know' 1 'All sworn' 2 'Some sworn'
             3 'Not authorized' /
   SAFE_AUTH_SOFT -9 'Unknown/does not know' 1 'All sworn' 2 'Some sworn'
             3 'Not authorized' /
   SAFE_AUTH_SPRAY -9 'Unknown/does not know' 1 'All sworn' 2 'Some sworn'
             3 'Not authorized' /
   SAFE_AUTH_CHEM -9 'Unknown/does not know' 1 'All sworn' 2 'Some sworn'
             3 'Not authorized' /
   SAFE_AUTH_TASR -9 'Unknown/does not know' 1 'All sworn' 2 'Some sworn'
             3 'Not authorized' /
   SAFE_AUTH_NECK -9 'Unknown/does not know' 1 'All sworn' 2 'Some sworn'
             3 'Not authorized' /
   SAFE_AUTH_TKDWN -9 'Unknown/does not know' 1 'All sworn' 2 'Some sworn'
             3 'Not authorized' /
   SAFE_AUTH_OHAND -9 'Unknown/does not know' 1 'All sworn' 2 'Some sworn'
             3 'Not authorized' /
   SAFE_AUTH_CHAND -9 'Unknown/does not know' 1 'All sworn' 2 'Some sworn'
             3 'Not authorized' /
   SAFE_AUTH_LEG -9 'Unknown/does not know' 1 'All sworn' 2 'Some sworn'
             3 'Not authorized' /
   SAFE_DOC_DISF -8 'Not applicable' 1 'Yes' 2 'No' /
   SAFE_DOC_DCHF -8 'Not applicable' 1 'Yes' 2 'No' /
   SAFE_DOC_BAT -8 'Not applicable' 1 'Yes' 2 'No' /
   SAFE_DOC_IMP -8 'Not applicable' 1 'Yes' 2 'No' /
   SAFE_DOC_SOFT -8 'Not applicable' 1 'Yes' 2 'No' /
   SAFE_DOC_SPRAY -8 'Not applicable' 1 'Yes' 2 'No' /
   SAFE_DOC_CHEM -8 'Not applicable' 1 'Yes' 2 'No' /
   SAFE_DOC_DIST -8 'Not applicable' 1 'Yes' 2 'No' /
   SAFE_DOC_DCHT -8 'Not applicable' 1 'Yes' 2 'No' /
   SAFE_DOC_NECK -8 'Not applicable' 1 'Yes' 2 'No' /
   SAFE_DOC_TKDWN -8 'Not applicable' 1 'Yes' 2 'No' /
   SAFE_DOC_OHAND -8 'Not applicable' 1 'Yes' 2 'No' /
   SAFE_DOC_CHAND -8 'Not applicable' 1 'Yes' 2 'No' /
   SAFE_DOC_LEG -8 'Not applicable' 1 'Yes' 2 'No' /
   SAFE_FINC -9 'Unknown/does not know' 1 'Use of force form'
             2 'Documented in arrest report' 3 'No formal record' 4 'Other' /
   NO_RECORD_FORCE 1 'Yes-no recorded force' 2 'No' /
   SAFE_FRC_INC -8 'Not applicable (agency does not record use of force)'
             1 'Yes' 2 'No' /
   SAFE_FRC_OFFC -8 'Not applicable (agency does not record use of force)'
             1 'Yes' 2 'No' /
   SAFE_FRC_OTHR -8 'Not applicable (agency does not record use of force)'
             1 'Yes' 2 'No' /
   SAFE_FTTL -9 'Unknown/respondent does not know'
    -8 'Not applicable (did not record one use of force report per incident)'
             -3 'Invalid/missing response' /
   SAFE_FTTL_EST 1 'Yes-estimated' 2 'No' /
   SAFE_FTTL_UNK 1 'Yes-unknown' 2 'No' /
   SAFE_SEPR -9 'Unknown/respondent does not know'
    -8 'Not applicable (did not record one use of force report per incident)'
             -3 'Invalid/missing response' /
   SAFE_SEPR_EST 1 'Yes-estimated' 2 'No' /
   SAFE_SEPR_UNK 1 'Yes-unknown' 2 'No' /
   SAFE_ARMR 1 'No written policy on body armor' 2 'Agency selects'
             3 'Individual selects' 4 'Individual selects, w/ restrictions'
             5 'Other' /
   SAFE_ARMR_OTHRS -9 'Unknown/does not know' /
   SAFE_RQUR_ACC
             -8 'Not applicable (Agency has no written policy on body armor)'
             1 'Yes' 2 'No' /
   SAFE_RQUR_RSK
             -8 'Not applicable (Agency has no written policy on body armor)'
             1 'Yes' 2 'No' /
   SAFE_RQUR_ALL
             -8 'Not applicable (Agency has no written policy on body armor)'
             1 'Yes' 2 'No' /
   SAFE_RQUR_CSTM
             -8 'Not applicable (Agency has no written policy on body armor)'
             1 'Yes' 2 'No' /
   SAFE_RQUR_TRN
             -8 'Not applicable (Agency has no written policy on body armor)'
             1 'Yes' 2 'No' /
   SAFE_RQUR_COMP
             -8 'Not applicable (Agency has no written policy on body armor)'
             1 'Yes' 2 'No' /
   SAFE_RQUR_BLST
             -8 'Not applicable (Agency has no written policy on body armor)'
             1 'Yes' 2 'No' /
   NO_BODY_ARMOR 1 'Yes-none' 2 'No' /
   SAFE_PAY_DPT
             -8 'Not applicable (Agency has no written policy on body armor)'
             1 'Yes' 2 'No' /
   SAFE_PAY_IND
             -8 'Not applicable (Agency has no written policy on body armor)'
             1 'Yes' 2 'No' /
   SAFE_PAY_GRNT
             -8 'Not applicable (Agency has no written policy on body armor)'
             1 'Yes' 2 'No' /
   SAFE_PAY_OTHR
             -8 'Not applicable (Agency has no written policy on body armor)'
             1 'Yes' 2 'No' /
   ISSU_ADDR_BIAS -9 'Unknown/does not know'
             1 'Special unit with FULL-TIME personnel'
             2 'Special unit with part time personnel'
             3 'Dedicated personnel' 4 'No dedicated personnel'
             5 'Not formally addressed' /
   ISSU_ADDR_BOMB -9 'Unknown/does not know'
             1 'Special unit with FULL-TIME personnel'
             2 'Special unit with part time personnel'
             3 'Dedicated personnel' 4 'No dedicated personnel'
             5 'Not formally addressed' /
   ISSU_ADDR_ABSE -9 'Unknown/does not know'
             1 'Special unit with FULL-TIME personnel'
             2 'Special unit with part time personnel'
             3 'Dedicated personnel' 4 'No dedicated personnel'
             5 'Not formally addressed' /
   ISSU_ADDR_CYBR -9 'Unknown/does not know'
             1 'Special unit with FULL-TIME personnel'
             2 'Special unit with part time personnel'
             3 'Dedicated personnel' 4 'No dedicated personnel'
             5 'Not formally addressed' /
   ISSU_ADDR_DPV -9 'Unknown/does not know'
             1 'Special unit with FULL-TIME personnel'
             2 'Special unit with part time personnel'
             3 'Dedicated personnel' 4 'No dedicated personnel'
             5 'Not formally addressed' /
   ISSU_ADDR_TERR -9 'Unknown/does not know'
             1 'Special unit with FULL-TIME personnel'
             2 'Special unit with part time personnel'
             3 'Dedicated personnel' 4 'No dedicated personnel'
             5 'Not formally addressed' /
   ISSU_ADDR_TRAF -9 'Unknown/does not know'
             1 'Special unit with FULL-TIME personnel'
             2 'Special unit with part time personnel'
             3 'Dedicated personnel' 4 'No dedicated personnel'
             5 'Not formally addressed' /
   ISSU_ADDR_DUI -9 'Unknown/does not know'
             1 'Special unit with FULL-TIME personnel'
             2 'Special unit with part time personnel'
             3 'Dedicated personnel' 4 'No dedicated personnel'
             5 'Not formally addressed' /
   ISSU_ADDR_JUV -9 'Unknown/does not know'
             1 'Special unit with FULL-TIME personnel'
             2 'Special unit with part time personnel'
             3 'Dedicated personnel' 4 'No dedicated personnel'
             5 'Not formally addressed' /
   ISSU_ADDR_GANG -9 'Unknown/does not know'
             1 'Special unit with FULL-TIME personnel'
             2 'Special unit with part time personnel'
             3 'Dedicated personnel' 4 'No dedicated personnel'
             5 'Not formally addressed' /
   ISSU_ADDR_REEN -9 'Unknown/does not know'
             1 'Special unit with FULL-TIME personnel'
             2 'Special unit with part time personnel'
             3 'Dedicated personnel' 4 'No dedicated personnel'
             5 'Not formally addressed' /
   ISSU_ADDR_FUG -9 'Unknown/does not know'
             1 'Special unit with FULL-TIME personnel'
             2 'Special unit with part time personnel'
             3 'Dedicated personnel' 4 'No dedicated personnel'
             5 'Not formally addressed' /
   ISSU_ADDR_VIC -9 'Unknown/does not know'
             1 'Special unit with FULL-TIME personnel'
             2 'Special unit with part time personnel'
             3 'Dedicated personnel' 4 'No dedicated personnel'
             5 'Not formally addressed' /
   ISSU_ADDR_SWAT -9 'Unknown/does not know'
             1 'Special unit with FULL-TIME personnel'
             2 'Special unit with part time personnel'
             3 'Dedicated personnel' 4 'No dedicated personnel'
             5 'Not formally addressed' /
   ISSU_SPEC -9 'Unknown/does not know' /
   ISSU_MULTI -9 'Unknown/does not know' 1 'Yes' 2 'No' /
   ISSU_TASK_SWAT
        -8 'Not applicable (No multijurisdictional task force participation)'
             1 'Yes' 2 'No' /
   ISSU_TASK_DRUG
        -8 'Not applicable (No multijurisdictional task force participation)'
             1 'Yes' 2 'No' /
   ISSU_TASK_GANG
        -8 'Not applicable (No multijurisdictional task force participation)'
             1 'Yes' 2 'No' /
   ISSU_TASK_TRAF
        -8 'Not applicable (No multijurisdictional task force participation)'
             1 'Yes' 2 'No' /
   ISSU_TASK_OTHR
        -8 'Not applicable (No multijurisdictional task force participation)'
             1 'Yes' 2 'No' /
   .

* SPSS MISSING VALUES COMMAND.

* MISSING VALUES
     ORI7 ('-1') /
     FTSWORN (-9) /
     FTCIV (-9) /
     PTSWORN (-9) /
     PTCIV (-9) /
     PERS_PDSW_MFT (-9) /
     PERS_PDSW_MPT (-9) /
     PERS_PDSW_FFT (-9) /
     PERS_PDSW_FPT (-9) /
     PERS_FTS_WHT (-9) /
     PERS_FTS_BLK (-9) /
     PERS_FTS_HSP (-9) /
     PERS_FTS_IND (-9) /
     PERS_FTS_ASN (-9) /
     PERS_FTS_HAW (-9) /
     PERS_FTS_TWO (-9) /
     PERS_FTS_UNK (-9) /
     PERS_FTS_RACETOT (-9.0) /
     PERS_RESP_PATRL (-9) /
     PERS_RESP_INVST (-9) /
     PERS_RESP_JAIL (-9, -8) /
     PERS_RESP_CRT (-9) /
     PERS_RESP_OTHR (-9, -8) /
     PERS_SUP_CHF_M (-9) /
     PERS_SUP_CHF_F (-9) /
     PERS_SUP_INTM_M (-9, -8) /
     PERS_SUP_INTM_F (-9, -8) /
     PERS_SUP_SGT_M (-9, -8) /
     PERS_SUP_SGT_F (-9, -8) /
     PERS_SSW_FT (-9) /
     PERS_SSW_PT (-9) /
     PERS_UPSW (-9) /
     PERS_DUT_NONE (-9) /
     PERS_DUT_ADMN (-8, -9) /
     PERS_DUT_CLN (-8, -9) /
     PERS_DUT_LGL (-8, -9) /
     PERS_DUT_ACCT (-8, -9) /
     PERS_DUT_FSCI (-8, -9) /
     PERS_DUT_RSRCH (-8, -9) /
     PERS_DUT_HR (-8, -9) /
     PERS_DUT_IT (-8, -9) /
     PERS_DUT_VM (-8, -9) /
     PERS_DUT_CD (-8, -9) /
     PERS_DUT_CRT (-8, -9) /
     PERS_DUT_JAIL (-8, -9) /
     PERS_DUT_OTHR (-8, -9) /
     PERS_DUT_SPEC ('-9') /
     PAY_SAL_EXC_MIN (-9, -8) /
     PAY_SAL_EXC_MAX (-9, -8) /
     PAY_SAL_SGT_MIN (-9, -8) /
     PAY_SAL_SGT_MAX (-9, -8) /
     PAY_SAL_OFCR_MIN (-9, -8) /
     PAY_SAL_OFCR_MAX (-9, -8) /
     PAY_INCT_EDU (-9) /
     PAY_INCT_VOC (-9) /
     PAY_INCT_LANG (-9) /
     PAY_INCT_SPCL (-9) /
     PAY_INCT_HZRD (-9) /
     PAY_INCT_SD (-9) /
     PAY_INCT_RINC (-9) /
     PAY_INCT_MRT (-9) /
     PAY_INCT_OTHR (-9) /
     PAY_INCT_SPEC ('-9') /
     PAY_OUT (-9) /
     PAY_RST_NO (-9, -8) /
     PAY_RST_HRS (-9, -8) /
     PAY_RST_TYPE (-9, -8) /
     PAY_RST_OTHR (-9, -8) /
     PAY_RST_SPEC ('-9') /
     PAY_BARG (-9) /
     PAY_SBARG (-9, -8) /
     PAY_RMB_TUIT (-9) /
     PAY_RMB_UNF (-9) /
     PAY_RMB_ARMR (-9) /
     PAY_RMB_SFTY (-9) /
     PAY_RMB_FIRE (-9) /
     PAY_OVER_SW (-9) /
     PAY_OVER_NSW (-9) /
     PAY_FUNC_CRT (-9, -8) /
     PAY_FUNC_SHFT (-9, -8) /
     PAY_FUNC_PTRL (-9, -8) /
     PAY_FUNC_INVS (-9, -8) /
     PAY_FUNC_ADMN (-9, -8) /
     PAY_FUNC_EMRG (-9, -8) /
     PAY_FUNC_EVNT (-9, -8) /
     PAY_FUNC_OTHR (-9, -8) /
     PAY_FUNC_SPEC ('-9') /
     PAY_LMT (-9) /
     PAY_VEH_MRK (-9) /
     PAY_VEH_UMRK (-9) /
     HIR_FRZ (-9) /
     HIR_MTH_SW10 (-9, -8) /
     HIR_MTH_SW11 (-9, -8) /
     HIR_MTH_SW12 (-9, -8) /
     HIR_MTH_NSW10 (-9.0, -8.0) /
     HIR_MTH_NSW11 (-9.0, -8.0) /
     HIR_MTH_NSW12 (-9.0, -8.0) /
     HIR_NBR (-9) /
     HIR_NBR_DRCT_FT (-9, -8) /
     HIR_NBR_DRCT_PT (-9, -8) /
     HIR_NBR_PRE_FT (-9, -8) /
     HIR_NBR_PRE_PT (-9, -8) /
     HIR_NBR_LAT_FT (-9, -8) /
     HIR_NBR_LAT_PT (-9, -8) /
     HIR_NBR_TFT (-9, -8) /
     HIR_NBR_TPT (-9, -8) /
     HIR_TRN_NO_L (-9) /
     HIR_TRN_NO_P (-9) /
     HIR_TRN_CRS_L (-9) /
     HIR_TRN_CRS_P (-9) /
     HIR_TRN_FLD_L (-9) /
     HIR_TRN_FLD_P (-9) /
     HIR_TRN_DIR_L (-9) /
     HIR_TRN_DIR_P (-9) /
     HIR_TRN_OLATS ('-9') /
     HIR_TRN_OPRES ('-9') /
     HIR_NSWT_NO (-9) /
     HIR_NSWT_VAR_FT (-9, -8) /
     HIR_NSWT_VAR_PT (-9.0, -8.0) /
     HIR_EDU_NO (-9) /
     HIR_EDU_HS (-9) /
     HIR_EDU_SCOL (-9) /
     HIR_EDU_AD (-9) /
     HIR_EDU_BD (-9) /
     HIR_EDU_OTHR (-9) /
     HIR_EDU_SPEC ('-9') /
     HIR_MIL (-9, -8) /
     HIR_BD_VAR (-9, -8) /
     HIR_RTR_DB (-9) /
     HIR_RTR_DC (-9) /
     HIR_RTR_SS (-9) /
     HIR_RTR_OTHR (-9) /
     HIR_RTR_SPEC ('-9') /
     HIR_SEP_NMED (-9) /
     HIR_SEP_MED (-9) /
     HIR_SEP_VOL (-9) /
     HIR_SEP_LAYOFF (-9) /
     HIR_SEP_DIS (-9) /
     HIR_SEP_OTHR (-9) /
     HIR_SEP_TTL (-9) /
     HIR_SEPNS_LAYOFF (-9) /
     HIR_SEPNS_OTHR (-9) /
     HIR_SEPNS_TTL (-9) /
     BDGT_MNTH (-9) /
     BDGT_TTL (-9) /
     BDGT_SRC_MNC (-9) /
     BDGT_SRC_CNTY (-9) /
     BDGT_SRC_STATE (-9) /
     BDGT_SRC_FED (-9) /
     BDGT_SRC_CONT (-9) /
     BDGT_SRC_ASST (-9) /
     BDGT_SRC_FEE (-9) /
     BDGT_SRC_OTHR (-9) /
     BDGT_SRC_SPEC ('-9') /
     BDGT_RED (-9) /
     BDGT_PCT_SW (-9.0, -8.0) /
     BDGT_PCT_NSW (-9.0, -8.0) /
     BDGT_FUR (-9) /
     BDGT_FUR2_SW10 (-9, -8) /
     BDGT_FUR2_SW11 (-9, -8) /
     BDGT_FUR2_SW12 (-9, -8) /
     BDGT_FUR2_NSW10 (-9, -8) /
     BDGT_FUR2_NSW11 (-9, -8) /
     BDGT_FUR2_NSW12 (-9, -8) /
     COM_MIS (-9) /
     COM_TRN_REC (-8, -9) /
     COM_TRN_INSRV (-8, -9) /
     COM_SARA (-9, -8) /
     COM_NSARA (-9, -8) /
     COM_COL (-9) /
     COM_PTNR (-9) /
     COM_BT (-9) /
     COM_NBT (-9, -8) /
     COM_SURV (-9) /
     TECH_TYP_GUN (-9) /
     TECH_TYP_LIC (-9) /
     TECH_TYP_SMRT (-9) /
     TECH_TYP_VPUB (-9) /
     TECH_TYP_VVEH (-9) /
     TECH_TYP_VPAT (-9) /
     TECH_TYP_VWPN (-9) /
     TECH_TYP_VOTHR (-9) /
     TECH_EAC_MREC (-9) /
     TECH_EAC_DREC (-9) /
     TECH_EAC_CRIM (-9) /
     TECH_EAC_WARR (-9) /
     TECH_EAC_PROT (-9) /
     TECH_EAC_ADRS (-9) /
     TECH_CIR (-9) /
     TECH_CIR_SPEC ('-9') /
     TECH_CRS (-9) /
     TECH_CREC_INC (-9, -8) /
     TECH_CREC_SUM (-9, -8) /
     TECH_CREC_NAR (-9, -8) /
     TECH_CREC_OTHR (-9, -8) /
     TECH_CREC_SPEC ('-9') /
     TECH_REC_NAR (-9, -8) /
     TECH_REC_CODE (-9, -8) /
     TECH_REC_STAT (-9, -8) /
     TECH_REC_VIC (-9, -8) /
     TECH_REC_SUS (-9, -8) /
     TECH_REC_LOC (-9, -8) /
     TECH_REC_GEO (-9, -8) /
     TECH_REC_DATE (-9, -8) /
     TECH_WHO_NO (-9) /
     TECH_WHO_STAFF (-9, -8) /
     TECH_WHO_EXTR (-9, -8) /
     TECH_MANY_FTS (-9, -8) /
     TECH_MANY_PTS (-9, -8) /
     TECH_MANY_FTNS (-9, -8) /
     TECH_MANY_PTNS (-9, -8) /
     TECH_OUT_LAW (-9, -8) /
     TECH_OUT_GOV (-9, -8) /
     TECH_OUT_UNIV (-9, -8) /
     TECH_OUT_VEND (-9, -8) /
     TECH_OUT_OTHR (-9, -8) /
     TECH_OUT_OTHR_SPEC ('-9') /
     TECH_WEB_NONE (-9, -8) /
     TECH_WEB_JUR (-9, -8) /
     TECH_WEB_BEAT (-9, -8) /
     TECH_WEB_MAP (-9, -8) /
     TECH_WEB_OFFND (-9, -8) /
     TECH_WEB_OTHR (-9, -8) /
     TECH_WEB_SPEC ('-9') /
     TECH_PUBL_REP (-9, -8) /
     TECH_PUBL_ASK (-9, -8) /
     TECH_PUBL_FILE (-9, -8) /
     TECH_PUBL_OTHR (-9, -8) /
     TECH_PUBL_SPEC ('-9') /
     TECH_REPT (-9) /
     TECH_RECV (-9) /
     TECH_MEDIA_TW (-9) /
     TECH_MEDIA_FB (-9) /
     TECH_MEDIA_BLOG (-9) /
     TECH_MEDIA_YTBE (-9) /
     TECH_MEDIA_MASS (-9) /
     TECH_MEDIA_OTHR (-9) /
     TECH_MEDIA_SPEC ('-9') /
     VEH_OPRT_MK (-9) /
     VEH_OPRT_UNMK (-9) /
     VEH_TYP_MTR (-9) /
     VEH_TYP_ATV (-9) /
     VEH_TYP_AIR (-9) /
     VEH_TYP_HCOP (-9) /
     VEH_TYP_BOAT (-9) /
     VEH_TYP_DRONE (-9) /
     VEH_TYP_OTHR (-9) /
     VEH_TYP_SPEC ('-9') /
     VEH_WPUR (-9) /
     VEH_WPUR_SPEC ('-9') /
     VEH_DOC (-9) /
     VEH_DOC_SPEC ('-9') /
     VEH_NPUR (-9) /
     VEH_REST_ALN (-8) /
     VEH_REST_VISL (-8) /
     VEH_REST_SEPR (-8) /
     VEH_REST_RADIO (-8) /
     VEH_REST_ARM (-8) /
     VEH_REST_OTHR (-8) /
     VEH_REST_SPEC ('-9') /
     VEH_CNTN (-8) /
     SAFE_AUTH_HGN (-9) /
     SAFE_AUTH_RFL (-9) /
     SAFE_AUTH_SGN (-9) /
     SAFE_AUTH_BTN (-9) /
     SAFE_AUTH_IMP (-9) /
     SAFE_AUTH_SOFT (-9) /
     SAFE_AUTH_SPRAY (-9) /
     SAFE_AUTH_CHEM (-9) /
     SAFE_AUTH_TASR (-9) /
     SAFE_AUTH_NECK (-9) /
     SAFE_AUTH_TKDWN (-9) /
     SAFE_AUTH_OHAND (-9) /
     SAFE_AUTH_CHAND (-9) /
     SAFE_AUTH_LEG (-9) /
     SAFE_DOC_DISF (-8) /
     SAFE_DOC_DCHF (-8) /
     SAFE_DOC_BAT (-8) /
     SAFE_DOC_IMP (-8) /
     SAFE_DOC_SOFT (-8) /
     SAFE_DOC_SPRAY (-8) /
     SAFE_DOC_CHEM (-8) /
     SAFE_DOC_DIST (-8) /
     SAFE_DOC_DCHT (-8) /
     SAFE_DOC_NECK (-8) /
     SAFE_DOC_TKDWN (-8) /
     SAFE_DOC_OHAND (-8) /
     SAFE_DOC_CHAND (-8) /
     SAFE_DOC_LEG (-8) /
     SAFE_FINC (-9) /
     SAFE_FINC_SPEC ('-9') /
     SAFE_FRC_INC (-8) /
     SAFE_FRC_OFFC (-8) /
     SAFE_FRC_OTHR (-8) /
     SAFE_FRC_SPEC ('-9') /
     SAFE_FTTL (-9, -8, -3) /
     SAFE_SEPR (-9, -8, -3) /
     SAFE_ARMR_OTHRS (-9) /
     SAFE_RQUR_ACC (-8) /
     SAFE_RQUR_RSK (-8) /
     SAFE_RQUR_ALL (-8) /
     SAFE_RQUR_CSTM (-8) /
     SAFE_RQUR_TRN (-8) /
     SAFE_RQUR_COMP (-8) /
     SAFE_RQUR_BLST (-8) /
     SAFE_PAY_DPT (-8) /
     SAFE_PAY_IND (-8) /
     SAFE_PAY_GRNT (-8) /
     SAFE_PAY_OTHR (-8) /
     SAFE_PAY_SPEC ('-9') /
     ISSU_ADDR_BIAS (-9) /
     ISSU_ADDR_BOMB (-9) /
     ISSU_ADDR_ABSE (-9) /
     ISSU_ADDR_CYBR (-9) /
     ISSU_ADDR_DPV (-9) /
     ISSU_ADDR_TERR (-9) /
     ISSU_ADDR_TRAF (-9) /
     ISSU_ADDR_DUI (-9) /
     ISSU_ADDR_JUV (-9) /
     ISSU_ADDR_GANG (-9) /
     ISSU_ADDR_REEN (-9) /
     ISSU_ADDR_FUG (-9) /
     ISSU_ADDR_VIC (-9) /
     ISSU_ADDR_SWAT (-9) /
     ISSU_SPEC (-9) /
     ISSU_MULTI (-9) /
     ISSU_TASK_SWAT (-8) /
     ISSU_TASK_DRUG (-8) /
     ISSU_TASK_GANG (-8) /
     ISSU_TASK_TRAF (-8) /
     ISSU_TASK_OTHR (-8) /
     ISSU_TASK_SPEC ('-9') /
   .

EXECUTE.

* SPSS VARIABLE LEVEL COMMAND.

VARIABLE LEVEL
   POP2012
   FTSWORN
   FTCIV
   PTSWORN
   PTCIV
   PERS_PDSW_MFT
   PERS_PDSW_MPT
   PERS_PDSW_FFT
   PERS_PDSW_FPT
   PERS_FTS_WHT
   PERS_FTS_BLK
   PERS_FTS_HSP
   PERS_FTS_IND
   PERS_FTS_ASN
   PERS_FTS_HAW
   PERS_FTS_TWO
   PERS_FTS_UNK
   PERS_FTS_RACETOT
   PERS_RESP_PATRL
   PERS_RESP_INVST
   PERS_RESP_JAIL
   PERS_RESP_CRT
   PERS_RESP_OTHR
   PERS_SUP_CHF_M
   PERS_SUP_CHF_F
   PERS_SUP_INTM_M
   PERS_SUP_INTM_F
   PERS_SUP_SGT_M
   PERS_SUP_SGT_F
   PERS_SSW_FT
   PERS_SSW_PT
   PERS_UPSW
   PAY_SAL_EXC_MIN
   PAY_SAL_EXC_MAX
   PAY_SAL_SGT_MIN
   PAY_SAL_SGT_MAX
   PAY_SAL_OFCR_MIN
   PAY_SAL_OFCR_MAX
   HIR_MTH_SW10
   HIR_MTH_SW11
   HIR_MTH_SW12
   HIR_MTH_NSW10
   HIR_MTH_NSW11
   HIR_MTH_NSW12
   HIR_NBR_DRCT_FT
   HIR_NBR_DRCT_PT
   HIR_NBR_PRE_FT
   HIR_NBR_PRE_PT
   HIR_NBR_LAT_FT
   HIR_NBR_LAT_PT
   HIR_NBR_TFT
   HIR_NBR_TPT
   HIR_NSWT_VAR_FT
   HIR_NSWT_VAR_PT
   HIR_BD_VAR
   HIR_SEP_NMED
   HIR_SEP_MED
   HIR_SEP_VOL
   HIR_SEP_LAYOFF
   HIR_SEP_DIS
   HIR_SEP_OTHR
   HIR_SEP_TTL
   HIR_SEPNS_LAYOFF
   HIR_SEPNS_OTHR
   HIR_SEPNS_TTL
   BDGT_TTL
   BDGT_PCT_SW
   BDGT_PCT_NSW
   BDGT_FUR2_SW10
   BDGT_FUR2_SW11
   BDGT_FUR2_SW12
   BDGT_FUR2_NSW10
   BDGT_FUR2_NSW11
   BDGT_FUR2_NSW12
   COM_NSARA
   COM_NBT
   TECH_MANY_FTS
   TECH_MANY_PTS
   TECH_MANY_FTNS
   TECH_MANY_PTNS
   VEH_OPRT_MK
   VEH_OPRT_UNMK
   VEH_NPUR
   SAFE_FTTL
   SAFE_SEPR
   SAFE_ARMR_OTHRS
   ISSU_SPEC
   BASEWT
   NRADJUST
   FINALWT
    (scale).

VARIABLE LEVEL
   ORI7
   ORI9
   SHERIFF_FLAG
   TYPE
   TRIBALPD
   COUNTYPD
   AGENCYID
   BJS_AGENCYNAME
   CITY
   STATENAME
   STATECODE
   ZIPCODE
   SAMPLETYPE_FINAL
   STRATCODE
   PERS_DUT_NONE
   PERS_DUT_ADMN
   PERS_DUT_CLN
   PERS_DUT_LGL
   PERS_DUT_ACCT
   PERS_DUT_FSCI
   PERS_DUT_RSRCH
   PERS_DUT_HR
   PERS_DUT_IT
   PERS_DUT_VM
   PERS_DUT_CD
   PERS_DUT_CRT
   PERS_DUT_JAIL
   PERS_DUT_OTHR
   PERS_DUT_SPEC
   PAY_INCT_EDU
   PAY_INCT_VOC
   PAY_INCT_LANG
   PAY_INCT_SPCL
   PAY_INCT_HZRD
   PAY_INCT_SD
   PAY_INCT_RINC
   PAY_INCT_MRT
   PAY_INCT_OTHR
   PAY_INCT_SPEC
   PAY_OUT
   PAY_RST_NO
   PAY_RST_HRS
   PAY_RST_TYPE
   PAY_RST_OTHR
   PAY_RST_SPEC
   PAY_BARG
   PAY_SBARG
   PAY_RMB_TUIT
   PAY_RMB_UNF
   PAY_RMB_ARMR
   PAY_RMB_SFTY
   PAY_RMB_FIRE
   PAY_OVER_SW
   PAY_OVER_NSW
   PAY_FUNC_CRT
   PAY_FUNC_SHFT
   PAY_FUNC_PTRL
   PAY_FUNC_INVS
   PAY_FUNC_ADMN
   PAY_FUNC_EMRG
   PAY_FUNC_EVNT
   PAY_FUNC_OTHR
   PAY_FUNC_SPEC
   PAY_LMT
   PAY_VEH_MRK
   PAY_VEH_UMRK
   HIR_FRZ
   HIR_NBR
   HIR_TRN_NO_L
   HIR_TRN_NO_P
   HIR_TRN_CRS_L
   HIR_TRN_CRS_P
   HIR_TRN_FLD_L
   HIR_TRN_FLD_P
   HIR_TRN_DIR_L
   HIR_TRN_DIR_P
   HIR_TRN_OLATS
   HIR_TRN_OPRES
   HIR_NSWT_NO
   HIR_EDU_NO
   HIR_EDU_HS
   HIR_EDU_SCOL
   HIR_EDU_AD
   HIR_EDU_BD
   HIR_EDU_OTHR
   HIR_EDU_SPEC
   HIR_MIL
   HIR_RTR_DB
   HIR_RTR_DC
   HIR_RTR_SS
   HIR_RTR_OTHR
   HIR_RTR_SPEC
   BDGT_MNTH
   BDGT_TTL_EST
   BDGT_SRC_MNC
   BDGT_SRC_CNTY
   BDGT_SRC_STATE
   BDGT_SRC_FED
   BDGT_SRC_CONT
   BDGT_SRC_ASST
   BDGT_SRC_FEE
   BDGT_SRC_OTHR
   BDGT_SRC_SPEC
   BDGT_RED
   BDGT_FUR
   COM_MIS
   COM_TRN_REC
   COM_TRN_INSRV
   COM_SARA
   COM_COL
   COM_PTNR
   COM_BT
   COM_SURV
   TECH_TYP_GUN
   TECH_TYP_LIC
   TECH_TYP_SMRT
   TECH_TYP_VPUB
   TECH_TYP_VVEH
   TECH_TYP_VPAT
   TECH_TYP_VWPN
   TECH_TYP_VOTHR
   TECH_EAC_MREC
   TECH_EAC_DREC
   TECH_EAC_CRIM
   TECH_EAC_WARR
   TECH_EAC_PROT
   TECH_EAC_ADRS
   TECH_CIR
   TECH_CIR_SPEC
   TECH_CRS
   TECH_CREC_INC
   TECH_CREC_SUM
   TECH_CREC_NAR
   TECH_CREC_OTHR
   TECH_CREC_SPEC
   TECH_REC_NAR
   TECH_REC_CODE
   TECH_REC_STAT
   TECH_REC_VIC
   TECH_REC_SUS
   TECH_REC_LOC
   TECH_REC_GEO
   TECH_REC_DATE
   TECH_WHO_NO
   TECH_WHO_STAFF
   TECH_WHO_EXTR
   TECH_OUT_LAW
   TECH_OUT_GOV
   TECH_OUT_UNIV
   TECH_OUT_VEND
   TECH_OUT_OTHR
   TECH_OUT_OTHR_SPEC
   TECH_WEB_NONE
   TECH_WEB_JUR
   TECH_WEB_BEAT
   TECH_WEB_MAP
   TECH_WEB_OFFND
   TECH_WEB_OTHR
   TECH_WEB_SPEC
   TECH_PUBL_REP
   TECH_PUBL_ASK
   TECH_PUBL_FILE
   TECH_PUBL_OTHR
   TECH_PUBL_SPEC
   TECH_REPT
   TECH_RECV
   TECH_MEDIA_TW
   TECH_MEDIA_FB
   TECH_MEDIA_BLOG
   TECH_MEDIA_YTBE
   TECH_MEDIA_MASS
   TECH_MEDIA_OTHR
   TECH_MEDIA_SPEC
   VEH_TYP_MTR
   VEH_TYP_ATV
   VEH_TYP_AIR
   VEH_TYP_HCOP
   VEH_TYP_BOAT
   VEH_TYP_DRONE
   VEH_TYP_OTHR
   VEH_TYP_SPEC
   VEH_WPUR
   VEH_WPUR_SPEC
   VEH_DOC
   VEH_DOC_SPEC
   VEH_NPUR_EST
   VEH_NPUR_UNK
   VEH_REST_NO
   VEH_REST_ALN
   VEH_REST_VISL
   VEH_REST_SEPR
   VEH_REST_RADIO
   VEH_REST_ARM
   VEH_REST_OTHR
   VEH_REST_SPEC
   VEH_CNTN
   SAFE_AUTH_HGN
   SAFE_AUTH_RFL
   SAFE_AUTH_SGN
   SAFE_AUTH_BTN
   SAFE_AUTH_IMP
   SAFE_AUTH_SOFT
   SAFE_AUTH_SPRAY
   SAFE_AUTH_CHEM
   SAFE_AUTH_TASR
   SAFE_AUTH_NECK
   SAFE_AUTH_TKDWN
   SAFE_AUTH_OHAND
   SAFE_AUTH_CHAND
   SAFE_AUTH_LEG
   SAFE_DOC_DISF
   SAFE_DOC_DCHF
   SAFE_DOC_BAT
   SAFE_DOC_IMP
   SAFE_DOC_SOFT
   SAFE_DOC_SPRAY
   SAFE_DOC_CHEM
   SAFE_DOC_DIST
   SAFE_DOC_DCHT
   SAFE_DOC_NECK
   SAFE_DOC_TKDWN
   SAFE_DOC_OHAND
   SAFE_DOC_CHAND
   SAFE_DOC_LEG
   SAFE_FINC
   SAFE_FINC_SPEC
   NO_RECORD_FORCE
   SAFE_FRC_INC
   SAFE_FRC_OFFC
   SAFE_FRC_OTHR
   SAFE_FRC_SPEC
   SAFE_FTTL_EST
   SAFE_FTTL_UNK
   SAFE_SEPR_EST
   SAFE_SEPR_UNK
   SAFE_ARMR
   SAFE_RQUR_ACC
   SAFE_RQUR_RSK
   SAFE_RQUR_ALL
   SAFE_RQUR_CSTM
   SAFE_RQUR_TRN
   SAFE_RQUR_COMP
   SAFE_RQUR_BLST
   NO_BODY_ARMOR
   SAFE_PAY_DPT
   SAFE_PAY_IND
   SAFE_PAY_GRNT
   SAFE_PAY_OTHR
   SAFE_PAY_SPEC
   ISSU_ADDR_BIAS
   ISSU_ADDR_BOMB
   ISSU_ADDR_ABSE
   ISSU_ADDR_CYBR
   ISSU_ADDR_DPV
   ISSU_ADDR_TERR
   ISSU_ADDR_TRAF
   ISSU_ADDR_DUI
   ISSU_ADDR_JUV
   ISSU_ADDR_GANG
   ISSU_ADDR_REEN
   ISSU_ADDR_FUG
   ISSU_ADDR_VIC
   ISSU_ADDR_SWAT
   ISSU_MULTI
   ISSU_TASK_SWAT
   ISSU_TASK_DRUG
   ISSU_TASK_GANG
   ISSU_TASK_TRAF
   ISSU_TASK_OTHR
   ISSU_TASK_SPEC
    (nominal).

* SPSS FORMAT COMMAND.

FORMAT
    ORI7 (A7) /
    ORI9 (A9) /
    SHERIFF_FLAG (F2.0) /
    TYPE (A1) /
    TRIBALPD (F2.0) /
    COUNTYPD (F2.0) /
    AGENCYID (A12) /
    BJS_AGENCYNAME (A100) /
    CITY (A40) /
    STATENAME (A20) /
    STATECODE (A2) /
    ZIPCODE (A5) /
    POP2012 (F8.0) /
    SAMPLETYPE_FINAL (A20) /
    STRATCODE (F3.0) /
    FTSWORN (F5.0) /
    FTCIV (F5.0) /
    PTSWORN (F3.0) /
    PTCIV (F4.0) /
    PERS_PDSW_MFT (F5.0) /
    PERS_PDSW_MPT (F3.0) /
    PERS_PDSW_FFT (F4.0) /
    PERS_PDSW_FPT (F3.0) /
    PERS_FTS_WHT (F5.0) /
    PERS_FTS_BLK (F4.0) /
    PERS_FTS_HSP (F4.0) /
    PERS_FTS_IND (F2.0) /
    PERS_FTS_ASN (F4.0) /
    PERS_FTS_HAW (F3.0) /
    PERS_FTS_TWO (F4.0) /
    PERS_FTS_UNK (F3.0) /
    PERS_FTS_RACETOT (F8.2) /
    PERS_RESP_PATRL (F4.0) /
    PERS_RESP_INVST (F4.0) /
    PERS_RESP_JAIL (F4.0) /
    PERS_RESP_CRT (F4.0) /
    PERS_RESP_OTHR (F4.0) /
    PERS_SUP_CHF_M (F2.0) /
    PERS_SUP_CHF_F (F2.0) /
    PERS_SUP_INTM_M (F4.0) /
    PERS_SUP_INTM_F (F3.0) /
    PERS_SUP_SGT_M (F4.0) /
    PERS_SUP_SGT_F (F3.0) /
    PERS_SSW_FT (F3.0) /
    PERS_SSW_PT (F3.0) /
    PERS_UPSW (F4.0) /
    PERS_DUT_NONE (F2.0) /
    PERS_DUT_ADMN (F2.0) /
    PERS_DUT_CLN (F2.0) /
    PERS_DUT_LGL (F2.0) /
    PERS_DUT_ACCT (F2.0) /
    PERS_DUT_FSCI (F2.0) /
    PERS_DUT_RSRCH (F2.0) /
    PERS_DUT_HR (F2.0) /
    PERS_DUT_IT (F2.0) /
    PERS_DUT_VM (F2.0) /
    PERS_DUT_CD (F2.0) /
    PERS_DUT_CRT (F2.0) /
    PERS_DUT_JAIL (F2.0) /
    PERS_DUT_OTHR (F2.0) /
    PERS_DUT_SPEC (A200) /
    PAY_SAL_EXC_MIN (F6.0) /
    PAY_SAL_EXC_MAX (F6.0) /
    PAY_SAL_SGT_MIN (F6.0) /
    PAY_SAL_SGT_MAX (F6.0) /
    PAY_SAL_OFCR_MIN (F6.0) /
    PAY_SAL_OFCR_MAX (F6.0) /
    PAY_INCT_EDU (F2.0) /
    PAY_INCT_VOC (F2.0) /
    PAY_INCT_LANG (F2.0) /
    PAY_INCT_SPCL (F2.0) /
    PAY_INCT_HZRD (F2.0) /
    PAY_INCT_SD (F2.0) /
    PAY_INCT_RINC (F2.0) /
    PAY_INCT_MRT (F2.0) /
    PAY_INCT_OTHR (F2.0) /
    PAY_INCT_SPEC (A200) /
    PAY_OUT (F2.0) /
    PAY_RST_NO (F2.0) /
    PAY_RST_HRS (F2.0) /
    PAY_RST_TYPE (F2.0) /
    PAY_RST_OTHR (F2.0) /
    PAY_RST_SPEC (A200) /
    PAY_BARG (F2.0) /
    PAY_SBARG (F2.0) /
    PAY_RMB_TUIT (F2.0) /
    PAY_RMB_UNF (F2.0) /
    PAY_RMB_ARMR (F2.0) /
    PAY_RMB_SFTY (F2.0) /
    PAY_RMB_FIRE (F2.0) /
    PAY_OVER_SW (F2.0) /
    PAY_OVER_NSW (F2.0) /
    PAY_FUNC_CRT (F2.0) /
    PAY_FUNC_SHFT (F2.0) /
    PAY_FUNC_PTRL (F2.0) /
    PAY_FUNC_INVS (F2.0) /
    PAY_FUNC_ADMN (F2.0) /
    PAY_FUNC_EMRG (F2.0) /
    PAY_FUNC_EVNT (F2.0) /
    PAY_FUNC_OTHR (F2.0) /
    PAY_FUNC_SPEC (A200) /
    PAY_LMT (F2.0) /
    PAY_VEH_MRK (F2.0) /
    PAY_VEH_UMRK (F2.0) /
    HIR_FRZ (F2.0) /
    HIR_MTH_SW10 (F2.0) /
    HIR_MTH_SW11 (F2.0) /
    HIR_MTH_SW12 (F2.0) /
    HIR_MTH_NSW10 (F5.2) /
    HIR_MTH_NSW11 (F4.1) /
    HIR_MTH_NSW12 (F4.1) /
    HIR_NBR (F2.0) /
    HIR_NBR_DRCT_FT (F4.0) /
    HIR_NBR_DRCT_PT (F2.0) /
    HIR_NBR_PRE_FT (F2.0) /
    HIR_NBR_PRE_PT (F2.0) /
    HIR_NBR_LAT_FT (F2.0) /
    HIR_NBR_LAT_PT (F2.0) /
    HIR_NBR_TFT (F4.0) /
    HIR_NBR_TPT (F2.0) /
    HIR_TRN_NO_L (F2.0) /
    HIR_TRN_NO_P (F2.0) /
    HIR_TRN_CRS_L (F2.0) /
    HIR_TRN_CRS_P (F2.0) /
    HIR_TRN_FLD_L (F2.0) /
    HIR_TRN_FLD_P (F2.0) /
    HIR_TRN_DIR_L (F2.0) /
    HIR_TRN_DIR_P (F2.0) /
    HIR_TRN_OLATS (A200) /
    HIR_TRN_OPRES (A200) /
    HIR_NSWT_NO (F2.0) /
    HIR_NSWT_VAR_FT (F3.0) /
    HIR_NSWT_VAR_PT (F5.1) /
    HIR_EDU_NO (F2.0) /
    HIR_EDU_HS (F2.0) /
    HIR_EDU_SCOL (F2.0) /
    HIR_EDU_AD (F2.0) /
    HIR_EDU_BD (F2.0) /
    HIR_EDU_OTHR (F2.0) /
    HIR_EDU_SPEC (A200) /
    HIR_MIL (F2.0) /
    HIR_BD_VAR (F3.0) /
    HIR_RTR_DB (F2.0) /
    HIR_RTR_DC (F2.0) /
    HIR_RTR_SS (F2.0) /
    HIR_RTR_OTHR (F2.0) /
    HIR_RTR_SPEC (A200) /
    HIR_SEP_NMED (F4.0) /
    HIR_SEP_MED (F2.0) /
    HIR_SEP_VOL (F3.0) /
    HIR_SEP_LAYOFF (F2.0) /
    HIR_SEP_DIS (F2.0) /
    HIR_SEP_OTHR (F3.0) /
    HIR_SEP_TTL (F4.0) /
    HIR_SEPNS_LAYOFF (F2.0) /
    HIR_SEPNS_OTHR (F4.0) /
    HIR_SEPNS_TTL (F4.0) /
    BDGT_MNTH (F2.0) /
    BDGT_TTL (F10.0) /
    BDGT_TTL_EST (F2.0) /
    BDGT_SRC_MNC (F2.0) /
    BDGT_SRC_CNTY (F2.0) /
    BDGT_SRC_STATE (F2.0) /
    BDGT_SRC_FED (F2.0) /
    BDGT_SRC_CONT (F2.0) /
    BDGT_SRC_ASST (F2.0) /
    BDGT_SRC_FEE (F2.0) /
    BDGT_SRC_OTHR (F2.0) /
    BDGT_SRC_SPEC (A200) /
    BDGT_RED (F2.0) /
    BDGT_PCT_SW (F5.2) /
    BDGT_PCT_NSW (F5.2) /
    BDGT_FUR (F2.0) /
    BDGT_FUR2_SW10 (F4.0) /
    BDGT_FUR2_SW11 (F4.0) /
    BDGT_FUR2_SW12 (F4.0) /
    BDGT_FUR2_NSW10 (F4.0) /
    BDGT_FUR2_NSW11 (F4.0) /
    BDGT_FUR2_NSW12 (F4.0) /
    COM_MIS (F2.0) /
    COM_TRN_REC (F2.0) /
    COM_TRN_INSRV (F2.0) /
    COM_SARA (F2.0) /
    COM_NSARA (F4.0) /
    COM_COL (F2.0) /
    COM_PTNR (F2.0) /
    COM_BT (F2.0) /
    COM_NBT (F4.0) /
    COM_SURV (F2.0) /
    TECH_TYP_GUN (F2.0) /
    TECH_TYP_LIC (F2.0) /
    TECH_TYP_SMRT (F2.0) /
    TECH_TYP_VPUB (F2.0) /
    TECH_TYP_VVEH (F2.0) /
    TECH_TYP_VPAT (F2.0) /
    TECH_TYP_VWPN (F2.0) /
    TECH_TYP_VOTHR (F2.0) /
    TECH_EAC_MREC (F2.0) /
    TECH_EAC_DREC (F2.0) /
    TECH_EAC_CRIM (F2.0) /
    TECH_EAC_WARR (F2.0) /
    TECH_EAC_PROT (F2.0) /
    TECH_EAC_ADRS (F2.0) /
    TECH_CIR (F2.0) /
    TECH_CIR_SPEC (A200) /
    TECH_CRS (F2.0) /
    TECH_CREC_INC (F2.0) /
    TECH_CREC_SUM (F2.0) /
    TECH_CREC_NAR (F2.0) /
    TECH_CREC_OTHR (F2.0) /
    TECH_CREC_SPEC (A200) /
    TECH_REC_NAR (F2.0) /
    TECH_REC_CODE (F2.0) /
    TECH_REC_STAT (F2.0) /
    TECH_REC_VIC (F2.0) /
    TECH_REC_SUS (F2.0) /
    TECH_REC_LOC (F2.0) /
    TECH_REC_GEO (F2.0) /
    TECH_REC_DATE (F2.0) /
    TECH_WHO_NO (F2.0) /
    TECH_WHO_STAFF (F2.0) /
    TECH_WHO_EXTR (F2.0) /
    TECH_MANY_FTS (F3.0) /
    TECH_MANY_PTS (F3.0) /
    TECH_MANY_FTNS (F3.0) /
    TECH_MANY_PTNS (F2.0) /
    TECH_OUT_LAW (F2.0) /
    TECH_OUT_GOV (F2.0) /
    TECH_OUT_UNIV (F2.0) /
    TECH_OUT_VEND (F2.0) /
    TECH_OUT_OTHR (F2.0) /
    TECH_OUT_OTHR_SPEC (A200) /
    TECH_WEB_NONE (F2.0) /
    TECH_WEB_JUR (F2.0) /
    TECH_WEB_BEAT (F2.0) /
    TECH_WEB_MAP (F2.0) /
    TECH_WEB_OFFND (F2.0) /
    TECH_WEB_OTHR (F2.0) /
    TECH_WEB_SPEC (A200) /
    TECH_PUBL_REP (F2.0) /
    TECH_PUBL_ASK (F2.0) /
    TECH_PUBL_FILE (F2.0) /
    TECH_PUBL_OTHR (F2.0) /
    TECH_PUBL_SPEC (A200) /
    TECH_REPT (F2.0) /
    TECH_RECV (F2.0) /
    TECH_MEDIA_TW (F2.0) /
    TECH_MEDIA_FB (F2.0) /
    TECH_MEDIA_BLOG (F2.0) /
    TECH_MEDIA_YTBE (F2.0) /
    TECH_MEDIA_MASS (F2.0) /
    TECH_MEDIA_OTHR (F2.0) /
    TECH_MEDIA_SPEC (A200) /
    VEH_OPRT_MK (F4.0) /
    VEH_OPRT_UNMK (F4.0) /
    VEH_TYP_MTR (F2.0) /
    VEH_TYP_ATV (F2.0) /
    VEH_TYP_AIR (F2.0) /
    VEH_TYP_HCOP (F2.0) /
    VEH_TYP_BOAT (F2.0) /
    VEH_TYP_DRONE (F2.0) /
    VEH_TYP_OTHR (F2.0) /
    VEH_TYP_SPEC (A200) /
    VEH_WPUR (F2.0) /
    VEH_WPUR_SPEC (A200) /
    VEH_DOC (F2.0) /
    VEH_DOC_SPEC (A200) /
    VEH_NPUR (F4.0) /
    VEH_NPUR_EST (F2.0) /
    VEH_NPUR_UNK (F2.0) /
    VEH_REST_NO (F2.0) /
    VEH_REST_ALN (F2.0) /
    VEH_REST_VISL (F2.0) /
    VEH_REST_SEPR (F2.0) /
    VEH_REST_RADIO (F2.0) /
    VEH_REST_ARM (F2.0) /
    VEH_REST_OTHR (F2.0) /
    VEH_REST_SPEC (A200) /
    VEH_CNTN (F2.0) /
    SAFE_AUTH_HGN (F2.0) /
    SAFE_AUTH_RFL (F2.0) /
    SAFE_AUTH_SGN (F2.0) /
    SAFE_AUTH_BTN (F2.0) /
    SAFE_AUTH_IMP (F2.0) /
    SAFE_AUTH_SOFT (F2.0) /
    SAFE_AUTH_SPRAY (F2.0) /
    SAFE_AUTH_CHEM (F2.0) /
    SAFE_AUTH_TASR (F2.0) /
    SAFE_AUTH_NECK (F2.0) /
    SAFE_AUTH_TKDWN (F2.0) /
    SAFE_AUTH_OHAND (F2.0) /
    SAFE_AUTH_CHAND (F2.0) /
    SAFE_AUTH_LEG (F2.0) /
    SAFE_DOC_DISF (F2.0) /
    SAFE_DOC_DCHF (F2.0) /
    SAFE_DOC_BAT (F2.0) /
    SAFE_DOC_IMP (F2.0) /
    SAFE_DOC_SOFT (F2.0) /
    SAFE_DOC_SPRAY (F2.0) /
    SAFE_DOC_CHEM (F2.0) /
    SAFE_DOC_DIST (F2.0) /
    SAFE_DOC_DCHT (F2.0) /
    SAFE_DOC_NECK (F2.0) /
    SAFE_DOC_TKDWN (F2.0) /
    SAFE_DOC_OHAND (F2.0) /
    SAFE_DOC_CHAND (F2.0) /
    SAFE_DOC_LEG (F2.0) /
    SAFE_FINC (F2.0) /
    SAFE_FINC_SPEC (A200) /
    NO_RECORD_FORCE (F2.0) /
    SAFE_FRC_INC (F2.0) /
    SAFE_FRC_OFFC (F2.0) /
    SAFE_FRC_OTHR (F2.0) /
    SAFE_FRC_SPEC (A200) /
    SAFE_FTTL (F4.0) /
    SAFE_FTTL_EST (F2.0) /
    SAFE_FTTL_UNK (F2.0) /
    SAFE_SEPR (F6.0) /
    SAFE_SEPR_EST (F2.0) /
    SAFE_SEPR_UNK (F2.0) /
    SAFE_ARMR (F2.0) /
    SAFE_ARMR_OTHRS (F2.0) /
    SAFE_RQUR_ACC (F2.0) /
    SAFE_RQUR_RSK (F2.0) /
    SAFE_RQUR_ALL (F2.0) /
    SAFE_RQUR_CSTM (F2.0) /
    SAFE_RQUR_TRN (F2.0) /
    SAFE_RQUR_COMP (F2.0) /
    SAFE_RQUR_BLST (F2.0) /
    NO_BODY_ARMOR (F2.0) /
    SAFE_PAY_DPT (F2.0) /
    SAFE_PAY_IND (F2.0) /
    SAFE_PAY_GRNT (F2.0) /
    SAFE_PAY_OTHR (F2.0) /
    SAFE_PAY_SPEC (A200) /
    ISSU_ADDR_BIAS (F2.0) /
    ISSU_ADDR_BOMB (F2.0) /
    ISSU_ADDR_ABSE (F2.0) /
    ISSU_ADDR_CYBR (F2.0) /
    ISSU_ADDR_DPV (F2.0) /
    ISSU_ADDR_TERR (F2.0) /
    ISSU_ADDR_TRAF (F2.0) /
    ISSU_ADDR_DUI (F2.0) /
    ISSU_ADDR_JUV (F2.0) /
    ISSU_ADDR_GANG (F2.0) /
    ISSU_ADDR_REEN (F2.0) /
    ISSU_ADDR_FUG (F2.0) /
    ISSU_ADDR_VIC (F2.0) /
    ISSU_ADDR_SWAT (F2.0) /
    ISSU_SPEC (F3.0) /
    ISSU_MULTI (F2.0) /
    ISSU_TASK_SWAT (F2.0) /
    ISSU_TASK_DRUG (F2.0) /
    ISSU_TASK_GANG (F2.0) /
    ISSU_TASK_TRAF (F2.0) /
    ISSU_TASK_OTHR (F2.0) /
    ISSU_TASK_SPEC (A200) /
    BASEWT (F6.3) /
    NRADJUST (F5.3) /
    FINALWT (F6.3) /

* Create SPSS system file.

*SAVE OUTFILE="spss-filename.sav".
